'use strict';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=v=>new Intl.NumberFormat('th-TH').format(v??0);
const labels={reasoning:'เหตุผลในการเลือก',direction:'ทิศทางเพจ',execution_across_six:'การลงมือทำทั้ง 6 EP',brief_completion:'ทำครบตามโจทย์',creativity:'ความคิดสร้างสรรค์',communication_quality:'คุณภาพการสื่อสาร',reflection:'การเรียนรู้และปรับปรุง',consistency:'ความสม่ำเสมอ',channel_direction:'ทิศทางช่อง',sales_communication:'การสื่อสารเพื่อขาย',presenter_continuity:'ความต่อเนื่องของพรีเซนเตอร์'};
let data,selectedEp='1',page=0;const pageSize=20;
function safeUrl(u){try{const x=new URL(u);return x.protocol==='https:'?esc(x.href):'#'}catch{return '#'}}
function sourceLink(e){return `<a class="evidence-link" href="${safeUrl(e.url)}" target="_blank" rel="noopener noreferrer">↗ ${esc(e.label||e.id||'ดูผลงานต้นฉบับ')}</a>`}
function dots(p){return `<div class="ep-dots" aria-label="ส่งการบ้านภายในกำหนด">${['1','2','3','4','5','6'].map(e=>`<span class="ep-dot ${p.submittedOnTime.includes(e)?'yes':''}" title="EP${e}: ${p.submittedOnTime.includes(e)?'ส่งภายในกำหนด':'ยังไม่พบการส่งในเวลา'}">${e}</span>`).join('')}</div>`}
function status(p){if(p.awards?.length)return '<span class="badge winner">ได้รับรางวัล</span>';if(Object.keys(p.reviews||{}).length)return '<span class="badge">มีข้อเสนอแนะแล้ว</span>';return '<span class="badge">รอตรวจหลักฐาน</span>'}
function renderEpisode(){const e=data.episodes.find(e=>e.id===selectedEp);$('#ep-tabs').innerHTML=data.episodes.map(x=>`<button role="tab" id="tab-${x.id}" aria-controls="episode" aria-selected="${x.id===selectedEp}" tabindex="${x.id===selectedEp?'0':'-1'}" data-ep="${x.id}">EP${x.id}</button>`).join('');$('#episode').setAttribute('aria-labelledby','tab-'+e.id);
  const winners=(e.winnerIds||[]).map(id=>data.people.find(p=>p.id===id)).filter(Boolean);
  $('#episode').innerHTML=`<div class="episode-box"><div class="episode-summary"><div><h3>${esc(e.title)}</h3><p>${esc(e.brief)}</p></div><div class="prize"><strong>${esc(e.prize)}</strong><span>${number(e.prizeCount)} รางวัล</span></div></div><div class="criteria">${Object.entries(e.weights).map(([k,v])=>`<span>${esc(labels[k]||k)} <b>${v}</b></span>`).join('')}</div>${e.specialRule?`<div class="notice">${esc(e.specialRule)}</div>`:''}${winners.length?`<div class="winners">${winners.map(p=>{const r=p.reviews?.[e.id];return `<article class="winner"><span class="award-label">${data.releaseStatus==='final'?'ได้รับรางวัล':'รายชื่อเสนอพิจารณา'} · EP${e.id}</span><h3>${esc(p.displayName)}</h3><p>${esc(r?.decisionReason||'')}</p><button class="text-button" data-person="${esc(p.id)}">อ่านเหตุผลและหลักฐาน →</button></article>`}).join('')}</div>`:`<div class="notice">${esc(e.pendingMessage||'กำลังตรวจหลักฐานและเปรียบเทียบผลงาน ยังไม่มีการประกาศผู้ชนะใน EP นี้')}</div>`}${e.source?sourceLink({url:e.source,label:'ดูโจทย์และรางวัลจากสไลด์ EP'+e.id}):''}</div>`;
}
function filtered(){const q=$('#search').value.trim().toLocaleLowerCase('th');const ep=$('#ep-filter').value,s=$('#status-filter').value;return data.people.filter(p=>(!q||[p.displayName,...p.channels.map(c=>c.name)].join(' ').toLocaleLowerCase('th').includes(q))&&(ep==='all'||p.submitted.includes(ep))&&(s==='all'||s==='winner'&&p.awards?.length||s==='reviewed'&&Object.keys(p.reviews||{}).length>0||s==='complete'&&p.submittedOnTime.length===6||s==='pending'&&p.status!=='reviewed'));}
function renderPeople(){const rows=filtered(),pages=Math.max(1,Math.ceil(rows.length/pageSize));page=Math.min(page,pages-1);$('#people-count').textContent=`พบ ${number(rows.length)} คน`;$('#people-list').innerHTML=rows.slice(page*pageSize,(page+1)*pageSize).map(p=>`<button class="person-row" data-person="${esc(p.id)}"><span><strong>${esc(p.displayName)}</strong><span class="channel-names">${esc(p.channels.map(c=>c.name).filter(Boolean).join(' · ')||'ยังไม่มีชื่อช่องที่ตรวจสอบได้')}</span></span>${dots(p)}<span class="row-status">${status(p)}</span><span class="arrow" aria-hidden="true">↗</span></button>`).join('')||'<div class="empty">ไม่พบผลงานที่ตรงกับการค้นหา ลองเปลี่ยนชื่อหรือตัวกรอง</div>';$('#page-count').textContent=`หน้า ${page+1} / ${pages}`;$('#prev').disabled=page===0;$('#next').disabled=page===pages-1;}
function channelFeedback(c){if(!c.feedback)return '';return `<div class="channel-feedback"><p class="eyebrow">ตรวจภาพและเสียงจากตัวอย่าง ${number(c.sampleCount)} คลิป</p><p>${esc(c.feedback)}</p><div class="feedback-grid"><div><h4>จุดแข็งจากคลิปที่ตรวจ</h4><ul>${(c.strengths||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div><h4>ข้อเสนอแนะสำหรับช่องนี้</h4><ul>${(c.improvements||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></div><p class="small">ข้อสังเกตนี้มาจากตัวอย่างที่เข้าถึงได้ ยังไม่ใช่การรับรองทุกคลิปในช่อง และยังไม่ใช่ผลรางวัล</p>${(c.evidence||[]).map(sourceLink).join('')}</div>`;}
function calendar(c,ep){const start=data.episodes.find(x=>x.id===ep)?.startDate;if(!start||!c.dailyCounts)return '';const days=[];for(let d=new Date(start+'T00:00:00Z');d.toISOString().slice(0,10)<=data.cutoffDate;d.setUTCDate(d.getUTCDate()+1)){const date=d.toISOString().slice(0,10),n=c.dailyCounts[date]||0,target=data.episodes.find(x=>x.id===ep)?.dailyTarget||1;days.push(`<span class="day ${n>=target?'target':n?'active':''}" title="${esc(date)}: พบ ${n} คลิป"><span>${d.getUTCDate()}</span><b>${n||'·'}</b></span>`)}return `<div class="calendar" aria-label="จำนวนคลิปที่ตรวจพบรายวัน">${days.join('')}</div><p class="small">ตารางนี้นับคลิปที่พบทั้งหมด ยังไม่ได้ยืนยันว่าเป็นคลิปขายหรือผ่านโจทย์ทุกชิ้น · ช่องว่างหมายถึงยังไม่พบหลักฐาน และไม่ถือเป็นคะแนนศูนย์</p>`;}
function detail(p){$('#person-detail').innerHTML=`<div class="person-heading"><p class="eyebrow">ผลงานผู้เรียน รุ่น 3</p><h2 id="person-title">${esc(p.displayName)}</h2>${dots(p)}<p>${p.submittedOnTime.length===6?'<span class="badge complete">ส่งครบ 6 EP ภายในกำหนด — ผ่านเงื่อนไขส่งครบของ EP1</span>':'<span class="badge">ยังไม่ผ่านเงื่อนไขส่งครบ 6 EP สำหรับรางวัล EP1</span>'}</p>${p.identityNote?`<p class="small">${esc(p.identityNote)}</p>`:''}</div>${p.submitted.map(ep=>{const r=p.reviews?.[ep],e=data.episodes.find(e=>e.id===ep);return `<section class="detail-ep"><p class="eyebrow">EP${ep}</p><h3>${esc(e.title)}</h3>${r?`<p><span class="badge ${r.result==='winner'?'winner':''}">${esc(r.resultLabel||'ข้อเสนอแนะ')}</span></p>${r.decisionReason?`<p><strong>${esc(r.decisionReason)}</strong></p>`:''}<p>${esc(r.summary||'')}</p><div class="score-grid">${Object.entries(r.scores||{}).map(([k,v])=>`<div class="score"><span>${esc(labels[k]||k)}</span><strong>${v===null?'รอตรวจ':esc(v)} <span>/ ${e.weights[k]}</span></strong></div>`).join('')}</div><div class="feedback-grid"><div><h4>สิ่งที่ทำได้ดี</h4><ul>${(r.strengths||[]).map(s=>`<li>${esc(s)}</li>`).join('')}</ul></div><div><h4>สิ่งที่พัฒนาต่อได้</h4><ul>${(r.improvements||[]).map(s=>`<li>${esc(s)}</li>`).join('')}</ul></div></div>${r.coverage?`<p class="small">ขอบเขตหลักฐาน: ${esc(r.coverage)}</p>`:''}${(r.evidence||[]).map(sourceLink).join('')}`:'<p class="notice">อยู่ระหว่างตรวจหลักฐานของ EP นี้ ยังไม่สรุปคะแนนหรือผลรางวัล</p>'}${p.channels.filter(c=>c.episodes.includes(ep)).map(c=>`<div class="channel-block"><h4>${esc(c.name||'ช่องที่ส่งการบ้าน')}</h4>${sourceLink({url:c.url,label:'เปิดช่องต้นฉบับ'})}${c.creationNote?`<p class="small">${esc(c.creationNote)}</p>`:''}${calendar(c,ep)}${channelFeedback(c)}${c.coverage?`<p class="small">${esc(c.coverage)}</p>`:''}</div>`).join('')}</section>`}).join('')}`;$('#person-dialog').showModal();}
function openPerson(id){const p=data.people.find(p=>p.id===id);if(!p)return;detail(p);history.replaceState(null,'','#person='+encodeURIComponent(id));}
function closePerson(){$('#person-dialog').close();if(location.hash.startsWith('#person='))history.replaceState(null,'','#participants');}
function method(){const rules=[['EP1 ต้องส่งครบทั้ง 6 EP','ผู้รับรางวัลใหญ่ EP1 ต้องมีการส่งงานที่ครอบคลุม EP1, EP2, EP3–4, EP5 และ EP6 ภายในวันปิดรับ การส่งครบเป็นเงื่อนไขเข้าสู่การพิจารณา ยังต้องผ่านการประเมินคุณภาพผลงานด้วย'],['EP3 กับ EP4 แยกรางวัล','EP3 แจก KCUT 5 รางวัล และ EP4 แจก KVID 3 รางวัล ใช้เกณฑ์ของแต่ละ EP แม้ส่งผ่านฟอร์มเดียวกัน ผู้เรียนคนเดิมรับรางวัลได้มากกว่าหนึ่ง EP'],['วัดความสม่ำเสมอถึงวันปิดรับ','พิจารณาเฉพาะผลงานที่เผยแพร่ถึงวันที่ 7 กันยายน 2569 เวลา 23:59 น. ประเทศไทย โดยใช้ความสม่ำเสมอถึงกำหนดนี้แทนเงื่อนไขทำครบหนึ่งเดือนของ EP3–4'],['คุณภาพต้องมีหลักฐานจากเนื้อหา','พิจารณาความคิดสร้างสรรค์ การสื่อสาร ความต่อเนื่องของตัวละคร และความตรงโจทย์จากคลิปที่ตรวจจริง พร้อมระบุขอบเขตการตรวจในผลรายบุคคล ยอดชมและปฏิสัมพันธ์ที่ดึงหลังปิดรับใช้ประกอบบริบท ไม่มีผลต่อคะแนน'],['ข้อมูลไม่ครบ ≠ ผลงานไม่มี','ลิงก์เสีย เนื้อหาที่ลบหรือจำกัดการเข้าถึง และข้อจำกัดของการเก็บข้อมูลจะแสดงเป็นหลักฐานที่ยังตรวจไม่ได้ จะไม่แต่งข้อมูลหรืออ้างว่าดูคลิปที่เปิดไม่ได้'],['ข้อเสนอแนะมุ่งที่ผลงาน','ไม่นำอายุ เรื่องส่วนตัว ความยากลำบาก การซื้อสินค้า หรือคำชื่นชมผู้สอนมาให้คะแนน ไม่แสดงเบอร์โทร อีเมล หรือคำตอบส่วนตัวที่ไม่จำเป็นต่อการอธิบายผลงาน']];$('#method-content').innerHTML=rules.map(([h,p],i)=>`<details ${i===0?'open':''}><summary>${esc(h)}</summary><p>${esc(p)}</p></details>`).join('');}
async function init(){try{const res=await fetch('/awards-assets/results.json',{cache:'no-store'});if(!res.ok)throw Error('โหลดข้อมูลไม่สำเร็จ');data=await res.json();$('#release-status').textContent=data.releaseStatus==='final'?'ประกาศผลแล้ว':data.releaseStatus==='proposed'?'ผลเสนอพิจารณา — ยังไม่ประกาศทางการ':'อยู่ระหว่างตรวจหลักฐาน';$('#result-note').textContent='คนเดิมรับรางวัลได้มากกว่าหนึ่ง EP';$('#stats').innerHTML=[[data.people.length,'ผู้ส่งการบ้าน'],[data.stats.submissions,'รายการส่งทั้งหมด'],[data.people.filter(p=>p.submittedOnTime.length===6).length,'คนส่งครบ 6 EP ในเวลา'],[20,'รางวัลจาก 6 EP']].map(([n,l])=>`<div class="stat"><strong>${number(n)}</strong><span>${esc(l)}</span></div>`).join('');$('#updated-at').textContent='ข้อมูล ณ '+data.updatedLabel;renderEpisode();renderPeople();method();if(location.hash.startsWith('#person='))openPerson(decodeURIComponent(location.hash.slice(8)));}catch(e){$('#release-status').textContent='ยังโหลดผลไม่ได้';$('#load-error').hidden=false;$('#load-error').textContent='โหลดข้อมูลผลการพิจารณาไม่สำเร็จ กรุณาลองรีเฟรชหน้าอีกครั้ง';}}
document.addEventListener('click',e=>{const ep=e.target.closest('[data-ep]'),person=e.target.closest('[data-person]');if(ep){selectedEp=ep.dataset.ep;renderEpisode();$('#tab-'+selectedEp).focus()}if(person)openPerson(person.dataset.person)});$('#ep-tabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();let n=Number(selectedEp);selectedEp=String(e.key==='Home'?1:e.key==='End'?6:e.key==='ArrowLeft'?(n===1?6:n-1):(n===6?1:n+1));renderEpisode();$('#tab-'+selectedEp).focus()});for(const id of ['search','ep-filter','status-filter'])$('#'+id).addEventListener(id==='search'?'input':'change',()=>{page=0;renderPeople()});$('#prev').onclick=()=>{page--;renderPeople()};$('#next').onclick=()=>{page++;renderPeople()};$('#close-dialog').onclick=closePerson;$('#person-dialog').addEventListener('cancel',e=>{e.preventDefault();closePerson()});init();
