'use strict';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const img=v=>/^\/awards-assets\/winners-v[23]\/[a-zA-Z0-9_.-]+\.webp$/.test(v)?v:'';
const link=v=>{try{const u=new URL(v);return u.protocol==='https:'?esc(u.href):'#'}catch{return '#'}};
const channelButton=w=>new URL(w.channelUrl).hostname.endsWith('tiktok.com')?'เปิดช่อง TikTok ↗':'เปิดเพจ Facebook ↗';
const portfolioHtml=w=>w.portfolio?.length?`<section class="portfolio-section" id="winner-channels" aria-label="ช่องและผลงานของผู้ชนะ"><p class="eyebrow">จากไอเดียแรก สู่ผลงานหลายรูปแบบ</p><h3>ติดตามผลงานทั้ง ${w.portfolio.length} ช่องของคุณณัฐวุฒิ</h3><div class="portfolio-grid">${w.portfolio.map(c=>`<a class="portfolio-card" href="${link(c.url)}" target="_blank" rel="noopener noreferrer"><small>${esc(c.episodeLabel)}</small><h4>${esc(c.name)}</h4><p>${esc(c.description)}</p><span>เปิดเพจ Facebook ↗</span></a>`).join('')}</div></section>`:'';
const prizeArt={
 '1':{file:'macbook',alt:'น้อง KVID ถือ MacBook Neo สีเงิน'},
 '2':{file:'google-ai',alt:'น้อง KVID กับประกายแห่งการสร้างสรรค์ด้วย AI'},
 '3':{file:'kcut',alt:'น้อง KVID นำเสนอโลโก้ KCUT'},
 '4':{file:'kvid',alt:'น้อง KVID กับรางวัล KVID ตลอดชีพ'},
 '5':{file:'group',alt:'อ๊อฟและอีฟร่วมต้อนรับผู้เรียนกับน้อง KVID'},
 '6':{file:'group',alt:'อ๊อฟและอีฟร่วมต้อนรับผู้เรียนกับน้อง KVID'}
};
const prizePicture=(ep,cls='prize-art')=>`<img class="${cls}" src="/awards-assets/prizes-v9/${prizeArt[ep].file}-v01.webp" width="1200" height="800" alt="${prizeArt[ep].alt}">`;
const prizeVisual=ep=>`<div class="prize-visual">${prizePicture(ep)}${ep==='1'?`<a class="official-product" href="https://www.apple.com/newsroom/2026/03/say-hello-to-macbook-neo/" target="_blank" rel="noopener noreferrer" aria-label="ดูภาพ MacBook Neo จาก Apple"><img src="/awards-assets/prizes-v9/macbook-neo-official-v01.webp" width="500" height="334" alt="ภาพ MacBook Neo จาก Apple"><span>MacBook Neo ↗</span></a>`:''}</div>`;
let data,episode='1',active=0;const revealed=new Set();
function render(){
 $('#tabs').innerHTML=data.episodes.map(e=>`<button role="tab" id="ep-${e.id}" aria-selected="${episode===e.id}" aria-controls="awards" tabindex="${episode===e.id?0:-1}" data-ep="${e.id}">EP${e.id}</button>`).join('');
 const e=data.episodes.find(e=>e.id===episode),rows=data.winners.filter(w=>w.episode===episode);$('#awards').setAttribute('aria-labelledby','ep-'+episode);
 $('#awards').innerHTML=`<div class="ep-title"><p class="eyebrow">EPISODE ${episode.padStart(2,'0')}</p><h2>${esc(e.prize)}</h2><p>${e.count} รางวัลแห่งความตั้งใจ</p></div><div class="cards">${rows.map((w,i)=>`<article class="award-card">${prizeVisual(episode)}<small>EP${episode} · ผู้ได้รับรางวัล${rows.length>1?'คนที่ '+(i+1):''}</small>${revealed.has(w.key)?`<h3 class="winner-mini">${esc(w.fullName)}</h3><p class="channel-mini">${esc(w.channelName)}</p><button class="reveal-button" data-open="${w.key}">ชมผลงานผู้ชนะ</button><a class="winner-channel-button card-channel-button" href="${link(w.channelUrl)}" target="_blank" rel="noopener noreferrer">${channelButton(w)}</a>`:`<h3>${esc(w.prize)}</h3><button class="reveal-button" data-open="${w.key}">🎉 เปิดดูผู้ชนะ</button>`}</article>`).join('')}</div>`;
}
function show(key,unveil=true){const n=data.winners.findIndex(w=>w.key===key);if(n<0)return;active=n;if(unveil)revealed.add(key);renderStage();if(!$('#stage').open)$('#stage').showModal();if(unveil)render();}
function renderStage(){
 const w=data.winners[active];$('#stage-counter').textContent='EP'+w.episode+' · '+w.prize;$('#previous').disabled=active===0;$('#next').disabled=active===data.winners.length-1;
 const first=w.fullName.split(' ')[0],surname=w.fullName.slice(first.length).trim();
 $('#stage-content').innerHTML=revealed.has(w.key)?`<div class="winner-layout"><div class="winner-copy"><p class="eyebrow">🎉 ขอแสดงความยินดี</p><p class="prize">${prizePicture(w.episode,'prize-mini')}<span>${esc(w.prize)}</span></p><h2 id="winner-title" class="full-name"><span>${esc(first)}</span><span>${esc(surname)}</span></h2>${w.facebookName?`<p class="facebook-name">ชื่อ Facebook: ${esc(w.facebookName)}</p>`:''}<p class="channel-title">${esc(w.channelName)}</p><a class="winner-channel-button" href="${link(w.channelUrl)}" target="_blank" rel="noopener noreferrer">${channelButton(w)}</a>${w.portfolio?.length?`<button class="plain-button portfolio-jump" data-portfolio>ดูผลงานทั้ง ${w.portfolio.length} ช่อง ↓</button>`:''}<section class="winner-reasons" aria-label="เหตุผลที่ได้รับรางวัล"><h3>เหตุผลที่ได้รับรางวัล</h3>${w.reason.split(/\n\n+/).map(p=>`<p class="reason">${esc(p)}</p>`).join('')}</section><button class="plain-button copy-button" id="copy">คัดลอกข้อความประกาศ</button><div class="stage-status" id="copy-status" role="status"></div></div><div class="winner-images"><a class="channel-image-link" href="${link(w.channelUrl)}" target="_blank" rel="noopener noreferrer" aria-label="เปิดช่อง ${esc(w.channelName)}"><img class="channel-image" src="${img(w.channelImage)}" alt="ภาพช่อง ${esc(w.channelName)}"></a><a class="channel-link" href="${link(w.channelUrl)}" target="_blank" rel="noopener noreferrer">เปิดดูช่อง ${esc(w.channelName)} ↗</a><div class="clips">${w.clips.map(c=>`<a class="clip" href="${link(c.url)}" target="_blank" rel="noopener noreferrer" aria-label="เปิด ${esc(c.label)} ของ ${esc(w.channelName)}"><img src="${img(c.image)}" alt="${esc(c.label)}"><b aria-hidden="true">▶</b><span>${esc(c.label)} ↗</span></a>`).join('')}</div></div></div>${portfolioHtml(w)}`:`<div class="envelope"><p class="eyebrow">EP${w.episode} · รางวัลแห่งความตั้งใจ</p>${prizePicture(w.episode,'envelope-prize-art')}<h2 id="winner-title">${esc(w.prize)}</h2><button class="reveal-button" data-unveil="${w.key}">🎉 เปิดดูผู้ชนะ</button></div>`;
 $('#stage-content').scrollTop=0;
 const copy=$('#copy');if(copy)copy.onclick=async()=>{try{await navigator.clipboard.writeText('ขอแสดงความยินดีกับ'+(w.fullName.startsWith('คุณ')?'':'คุณ')+w.fullName+(w.facebookName?'\nชื่อ Facebook: '+w.facebookName:'')+'\n'+w.channelName+'\nได้รับรางวัล '+w.prize+' · EP'+w.episode+'\n\n'+w.reason+(w.portfolio?.length?'\n\nช่องและผลงานเพิ่มเติม\n'+w.portfolio.map(c=>c.name+' ('+c.episodeLabel+')\n'+c.url).join('\n\n'):'\n\nเปิดดูเพจหรือช่อง: '+w.channelUrl)+'\n\nhttps://businessboy.ai/gen3-awards');$('#copy-status').textContent='คัดลอกข้อความแล้ว พร้อมนำไปประกาศได้เลย'}catch{$('#copy-status').textContent='คัดลอกไม่สำเร็จ กรุณาเลือกข้อความแล้วคัดลอก'}};
}
function move(step){const n=active+step;if(n<0||n>=data.winners.length)return;active=n;renderStage();}
document.addEventListener('click',e=>{if(e.target.closest('[data-portfolio]')){document.querySelector('#winner-channels')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});return;}const ep=e.target.closest('[data-ep]'),open=e.target.closest('[data-open]'),unveil=e.target.closest('[data-unveil]');if(ep){episode=ep.dataset.ep;render();$('#ep-'+episode).focus({preventScroll:true})}if(open)show(open.dataset.open);if(unveil)show(unveil.dataset.unveil);});
$('#close-stage').onclick=()=>$('#stage').close();$('#previous').onclick=()=>move(-1);$('#next').onclick=()=>move(1);
document.addEventListener('keydown',e=>{if($('#stage').open&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();move(e.key==='ArrowLeft'?-1:1)}});
$('#tabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();episode=e.key==='Home'?'1':e.key==='End'?'6':String((Number(episode)-1+(e.key==='ArrowRight'?1:5))%6+1);render();$('#ep-'+episode).focus()});
fetch('/awards-assets/celebration.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{data=d;render()}).catch(()=>{$('#error').hidden=false});
