(() => {
'use strict';const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let state={},page=0,batch=null,exportRequest=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>Number(n||0).toLocaleString('th-TH'),date=s=>new Date(s).toLocaleString('th-TH',{timeZone:'Asia/Bangkok',dateStyle:'short',timeStyle:'short'}),num=o=>`BB${String(o.number).padStart(6,'0')}`;
const payments={awaiting_slip:'รอสลิป',review:'รอตรวจสลิป',paid:'รับเงินโอนแล้ว',cod_pending:'รอรับเงิน COD',cod_collected:'รับเงิน COD แล้ว',refunded:'คืนเงินแล้ว'},statuses={new:'เข้าใหม่',ready:'พร้อมส่ง',shipped:'ส่งแล้ว',delivered:'ส่งสำเร็จ',cancelled:'ยกเลิก',returned:'ส่งคืน'};
function message(s,error=false){$('#message').textContent=s;$('#message').hidden=!s;$('#message').classList.toggle('error',error);}
async function api(op,data={}){const r=await fetch(`/api/book?op=${op}`,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const d=await r.json();if(!r.ok){if(r.status===401){$('#login').hidden=false;$('#workspace').hidden=true;}throw Error(d.error||'ทำรายการไม่สำเร็จ');}return d;}
async function task(button,fn){button.disabled=true;try{await fn()}catch(e){message(e.message,true)}finally{button.disabled=false}}
function ready(o){return o.status==='ready'&&!o.batch_id&&(o.payment_status==='paid'||(o.method==='cod'&&o.payment_status==='cod_pending'));}
function draw(){const q=$('#search').value.trim().toLowerCase();$('#rows').innerHTML=state.orders.filter(o=>[num(o),o.first_name,o.last_name,o.phone,o.tracking||''].join(' ').toLowerCase().includes(q)).map(o=>`<tr><td><input type="checkbox" class="choose" value="${o.id}" aria-label="เลือก ${num(o)}" ${ready(o)?'':'disabled'}></td><td><b>${num(o)}</b><small>${date(o.created_at)}</small></td><td>${esc(o.first_name)} ${esc(o.last_name)}<small>${esc(o.phone)}</small><small>${esc(o.province)}</small></td><td>${o.package==='bundle'?'หนังสือ + เว็บ Prompt':'หนังสือ'}<small>${money(o.amount)} บาท • ส่งฟรี</small>${o.package==='bundle'?'<span class="badge green">ใส่ใบ QR ในกล่อง</span>':''}</td><td><span class="badge ${['paid','cod_collected'].includes(o.payment_status)?'green':'orange'}">${payments[o.payment_status]}</span><small>${o.method==='cod'?'เก็บปลายทาง':'โอนเงิน'}</small></td><td>${statuses[o.status]}<small>${o.batch_id?'ส่งออกไฟล์แล้ว':''}</small><small>${esc(o.tracking||'')}</small></td><td><button data-detail="${o.id}">ดู / จัดการ</button></td></tr>`).join('')||'<tr><td colspan="7">ยังไม่มีคำสั่งซื้อในรายการนี้</td></tr>';$$('[data-detail]').forEach(b=>b.onclick=()=>detail(state.orders.find(o=>o.id===b.dataset.detail)));$('#select-all').checked=false;$('#prev').disabled=page===0;$('#next').disabled=state.orders.length<100;$('#page-label').textContent=`หน้า ${page+1} • สูงสุด 100 รายการต่อหน้า`;}
async function load(){state=await api('admin',{page,status:$('#filter').value});$('#login').hidden=true;$('#workspace').hidden=false;$('#identity').textContent=state.user.email;draw();const m=state.metrics.orders;$('#metrics').innerHTML=[['ออเดอร์ทั้งหมด',m.count,'รายการ'],['ยอดสั่งซื้อ (ไม่รวมยกเลิก)',m.ordered,'บาท'],['ยอดรับเงินจริง',m.received,'บาท'],['COD รอรับเงิน',m.pending_cod,'บาท']].map(([label,v,unit])=>`<div class="metric"><span>${label}</span><strong>${money(v)}</strong> ${unit}</div>`).join('');
 $('#batches').innerHTML=state.batches.map(b=>`<div><span>${date(b.created_at)}<small> • ${b.id.slice(0,8)}</small></span><button data-batch="${b.id}">เปิดรอบ / ดาวน์โหลดซ้ำ</button></div>`).join('')||'<p class="micro">ยังไม่มีรอบส่งออก</p>';$$('[data-batch]').forEach(b=>b.onclick=()=>task(b,async()=>showBatch(await api('batch',{id:b.dataset.batch}))));
 const labels={page_view:'เปิดหน้า',checkout_start:'เริ่มกรอก',select_package:'เลือกแพ็กเกจ',order_submitted:'ส่งคำสั่งซื้อ',slip_uploaded:'ส่งสลิป',copy_account:'คัดลอกบัญชี',save_qr:'บันทึก QR',form_error:'พบข้อผิดพลาด',section_view:'เห็นส่วนเนื้อหา',payment_select:'เลือกการชำระ',engagement:'ช่วงการอ่าน',scroll:'เลื่อนหน้า'};
 $('#events').innerHTML=`<p>เวลาอ่านที่มีการใช้งานเฉลี่ย <b>${state.metrics.engagement} วินาที</b> ต่อช่วงการอ่าน</p><div class="status-grid">${state.metrics.events.map(e=>`<div class="metric"><span>${labels[e.event]||esc(e.event)}</span><strong>${money(e.visitors)}</strong> เซสชัน<small> / ${money(e.hits)} ครั้ง</small></div>`).join('')}</div>`;
 $('#sources').innerHTML=`<table><thead><tr><th>Source / Campaign</th><th>ออเดอร์</th><th>ยอดสั่ง</th><th>รับเงินจริง</th></tr></thead><tbody>${state.metrics.sources.map(s=>`<tr><td>${esc(s.source||'ตรง / ไม่ระบุ')}<small>${esc(s.campaign||'')}</small></td><td>${money(s.orders)}</td><td>${money(s.ordered)}</td><td>${money(s.received)}</td></tr>`).join('')||'<tr><td colspan="4">ยังไม่มีข้อมูล</td></tr>'}</tbody></table>`;
 for(const k of ['ga4_id','pixel_id','clarity_id'])$('#tracking-form').elements[k].value=state.settings[k];
 $('#tracking-form').hidden=state.user.role!=='owner';$('#staff-form').hidden=state.user.role!=='owner';$('#export').hidden=state.user.role==='finance';
 if(state.user.role==='owner')await staffList();
}
async function staffList(){const members=await api('staff_list');$('#staff').innerHTML=members.map(s=>`<div class="staff-row"><span>${esc(s.email)} • ${s.role} • ${s.active?'เปิดใช้งาน':'ปิดใช้งาน'}</span>${s.role!=='owner'&&s.active?`<button data-disable="${s.user_id}">ปิดสิทธิ์</button>`:''}</div>`).join('');$$('[data-disable]').forEach(b=>b.onclick=()=>task(b,async()=>{if(confirm('ปิดสิทธิ์สมาชิกคนนี้?')){await api('staff_disable',{id:b.dataset.disable});await staffList();message('ปิดสิทธิ์แล้ว');}}));}
function btn(action,text){return `<button class="button small ${action==='cancelled'||action==='reject_slip'?'secondary':''}" data-action="${action}">${text}</button>`;}
async function detail(o){const finance=['owner','finance'].includes(state.user.role),ship=['owner','fulfillment'].includes(state.user.role);let actions='';
 if(o.method==='cod'&&o.status==='new'&&ship)actions+=btn('ready','ยืนยันออเดอร์ COD พร้อมส่ง');
 if(o.payment_status==='review'&&o.status==='new'&&finance)actions+=`<button class="button secondary small" id="view-slip">เปิดสลิป</button>${btn('paid','ตรวจยอดเข้าแล้ว ยืนยันรับเงิน')}${btn('reject_slip','สลิปไม่ผ่าน ให้แนบใหม่')}`;
 if(o.status==='ready'&&o.batch_id&&ship)actions+=`<label>เลขพัสดุ DHL<input id="tracking" maxlength="60" placeholder="กรอกเลขพัสดุจริง"></label>${btn('shipped','บันทึกว่าจัดส่งแล้ว')}`;
 if(o.status==='shipped'&&ship)actions+=btn('delivered','ยืนยันจัดส่งสำเร็จ');
 if(o.status==='delivered'&&o.method==='cod'&&o.payment_status==='cod_pending'&&finance)actions+=btn('cod_collected','ตรวจยอด DHL แล้ว ยืนยันรับเงิน COD');
 if(['shipped','delivered'].includes(o.status)&&ship)actions+=btn('returned','บันทึกพัสดุส่งคืน');
 if(['new','ready'].includes(o.status)&&!o.batch_id)actions+=btn('cancelled','ยกเลิกคำสั่งซื้อ');
 if(['cancelled','returned'].includes(o.status)&&['paid','cod_collected'].includes(o.payment_status)&&finance)actions+=btn('refunded','คืนเงินจริงแล้ว บันทึกคืนเงิน');
 $('#detail-body').innerHTML=`<p class="eyebrow">${date(o.created_at)}</p><h2>${num(o)}</h2><p>${o.package==='bundle'?'หนังสือ + เว็บ Prompt (ใส่ใบ QR)':'หนังสือ 1 เล่ม'} • ${money(o.amount)} บาท</p><p>${payments[o.payment_status]} • ${statuses[o.status]}</p><div class="detail-info">${esc(`${o.first_name} ${o.last_name}\n${o.phone}\n${o.address}\n${o.subdistrict} ${o.district} ${o.province} ${o.postcode}\nหมายเหตุ: ${o.note||'-'}`)}</div><div class="actions">${actions}</div>${!o.batch_id&&['new','ready'].includes(o.status)?`<details><summary>แก้ชื่อ / เบอร์ / ที่อยู่ก่อนส่งออก</summary><form id="edit-order" class="form-grid edit-form">${[['first_name','ชื่อ'],['last_name','นามสกุล'],['phone','เบอร์โทร'],['address','ที่อยู่'],['subdistrict','ตำบล / แขวง'],['district','อำเภอ / เขต'],['province','จังหวัด'],['postcode','รหัสไปรษณีย์'],['note','หมายเหตุ']].map(([k,l])=>`<label>${l}<input name="${k}" value="${esc(o[k])}" ${k==='note'?'':'required'} maxlength="${k==='address'||k==='note'?500:100}"></label>`).join('')}<button class="button small" type="submit">บันทึกที่อยู่</button></form></details>`:''}<div class="audit" id="audit">กำลังโหลดประวัติ...</div>`;
 if(!$('#detail').open)$('#detail').showModal();
 $$('[data-action]').forEach(b=>b.onclick=()=>task(b,async()=>{if(!confirm(`${b.textContent} สำหรับ ${num(o)}?`))return;const result=await api('change',{id:o.id,revision:o.revision,action:b.dataset.action,data:{tracking:$('#tracking')?.value}});await load();await detail(result);message('บันทึกสถานะเรียบร้อย');}));
 if($('#view-slip'))$('#view-slip').onclick=()=>task($('#view-slip'),async()=>{const s=await api('slip_view',{id:o.id});$('#slip-image').src=s.url;$('#slip-dialog').showModal();});
 if($('#edit-order'))$('#edit-order').onsubmit=e=>{e.preventDefault();task(e.submitter,async()=>{const result=await api('change',{id:o.id,revision:o.revision,action:'edit',data:Object.fromEntries(new FormData(e.target))});await load();await detail(result);message('แก้ไขข้อมูลแล้ว');});};
 try{const audit=await api('audit',{id:o.id});$('#audit').innerHTML='<b>ประวัติการทำรายการ</b>'+audit.map(a=>`<div>${date(a.created_at)} • ${esc(a.action)}</div>`).join('');}catch(e){message(e.message,true)}
}
function showBatch(b){batch=b;$('#download-panel').hidden=false;$('#batch-label').textContent=`รอบ ${b.id.slice(0,8)} • ${b.orders.length} รายการ`;$('#download-panel').scrollIntoView({behavior:'smooth',block:'center'});}
$('#login').onsubmit=e=>{e.preventDefault();task(e.submitter,async()=>{await api('login',Object.fromEntries(new FormData(e.target)));e.target.reset();await load();message('เข้าสู่ระบบแล้ว');});};
$('#logout').onclick=()=>task($('#logout'),async()=>{await api('logout');location.reload()});
$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('.tab-panel').forEach(p=>p.hidden=p.id!==b.dataset.tab);$$('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));});
$('#reload').onclick=()=>task($('#reload'),load);$('#filter').onchange=()=>{page=0;load().catch(e=>message(e.message,true))};$('#search').oninput=draw;$('#prev').onclick=()=>{page--;load().catch(e=>message(e.message,true))};$('#next').onclick=()=>{page++;load().catch(e=>message(e.message,true))};
$('#select-all').onchange=e=>$$('.choose:not(:disabled)').forEach(x=>x.checked=e.target.checked);
$('#export').onclick=()=>task($('#export'),async()=>{const ids=$$('.choose:checked').map(x=>x.value).sort();if(!ids.length)throw Error('เลือกรายการพร้อมส่งก่อน');const signature=ids.join(',');if(!exportRequest||exportRequest.signature!==signature)exportRequest={signature,id:crypto.randomUUID()};showBatch(await api('export',{id:exportRequest.id,ids}));exportRequest=null;await load();message('สร้างรอบส่งออกแล้ว ดาวน์โหลดไฟล์ด้านล่างได้');});
$('#xlsx').onclick=()=>bookExport.download(bookExport.xlsx(batch.orders),`DHL-book-${batch.id.slice(0,8)}.xlsx`);$('#csv').onclick=()=>bookExport.download(bookExport.csv(batch.orders),`DHL-book-${batch.id.slice(0,8)}.csv`);
function printDoc(html){const w=window.open('','_blank');if(!w){message('กรุณาอนุญาตหน้าต่างใหม่เพื่อพิมพ์',true);return;}w.document.write(`<!doctype html><html lang="th"><meta charset="utf-8"><title>ใบแพ็กหนังสือ เด็กประกอบการ</title><link rel="stylesheet" href="/book-assets/print.css"><button id="print-now">พิมพ์ / บันทึก PDF</button>${html}</html>`);w.document.close();w.document.getElementById('print-now').addEventListener('click',()=>w.print());}
$('#packing').onclick=()=>printDoc(batch.orders.map(o=>`<div class="card"><h2>${num(o)}</h2><b>${esc(o.first_name)} ${esc(o.last_name)}</b><p>${esc(o.phone)}<br>${esc(o.address)}<br>${esc(o.subdistrict)} ${esc(o.district)} ${esc(o.province)} ${esc(o.postcode)}</p><b>□ หนังสือ 1 เล่ม ${o.package==='bundle'?' • □ ใบ QR และวิธีใช้เว็บ Prompt':''}</b><p>เก็บปลายทาง ${o.method==='cod'?o.amount:0} บาท<br>หมายเหตุ: ${esc(o.note||'-')}</p></div>`).join(''));
$('#print-insert').onclick=()=>task($('#print-insert'),async()=>{const data=await api('insert');printDoc(`<div class="card"><h2>เว็บรวม Prompt ในหนังสือ</h2><p>สำหรับผู้ซื้อชุดหนังสือพร้อมเว็บ Prompt</p><img src="/book-assets/prompt-qr.svg" alt="QR เข้าเว็บ Prompt"><p><b>businessboy.ai/promptbook</b><br>รหัสเข้าเว็บ: <b>${esc(data.code)}</b></p><ol><li>เปิดกล้องมือถือ แล้วสแกน QR ด้านบน</li><li>แตะลิงก์ และกรอกรหัสเข้าเว็บตามใบนี้</li><li>ค้นหาเรื่องที่ต้องการ แล้วกด “คัดลอก” Prompt</li><li>นำไปวางในเครื่องมือ AI ที่ใช้ แล้วปรับข้อมูลให้ตรงกับงาน</li></ol><p>เก็บใบนี้ไว้ใช้งานครั้งต่อไป<br>ติดขัดตรงไหน ติดต่อเพจเด็กประกอบการ</p></div>`);});
$('#link-builder').onsubmit=e=>{e.preventDefault();const u=new URL('https://businessboy.ai/ai-book');for(const [k,v] of new FormData(e.target))if(v)u.searchParams.set(k,v);$('#campaign-link').value=u.href;};$('#copy-link').onclick=()=>task($('#copy-link'),async()=>{if(!$('#campaign-link').value)throw Error('สร้างลิงก์ก่อน');await navigator.clipboard.writeText($('#campaign-link').value);message('คัดลอกลิงก์แล้ว')});
$('#tracking-form').onsubmit=e=>{e.preventDefault();task(e.submitter,async()=>{await api('settings',Object.fromEntries(new FormData(e.target)));message('บันทึก ID แล้ว ระบบจะโหลดตามความยินยอมของผู้ชม')});};$('#staff-form').onsubmit=e=>{e.preventDefault();task(e.submitter,async()=>{await api('staff_create',Object.fromEntries(new FormData(e.target)));e.target.reset();await staffList();message('เพิ่มสมาชิกแล้ว ส่งอีเมลและรหัสให้สมาชิกผ่านช่องทางส่วนตัวของทีม')});};
$('#close-detail').onclick=()=>$('#detail').close();$('#close-slip').onclick=()=>{$('#slip-dialog').close();$('#slip-image').removeAttribute('src')};load().catch(e=>{if(!/เข้าสู่ระบบ/.test(e.message))message(e.message,true)});
})();
