(() => {
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>Number(n||0).toLocaleString('th-TH'),date=s=>s?new Date(s).toLocaleString('th-TH',{timeZone:'Asia/Bangkok',dateStyle:'short',timeStyle:'short'}):'-',num=o=>'BB'+String(o.number).padStart(6,'0');
const products={prompt_upgrade:['เพิ่มเว็บ Prompt',145],kcut_month:['KCUT 1 เดือน',390],kcut_year:['KCUT 1 ปี',3900],kcut_lifetime:['KCUT ตลอดชีพ',5900]};
const payments={awaiting_slip:'รอโอนเงิน',review:'รอตรวจสลิป',paid:'รับเงินแล้ว',cod_pending:'รอรับเงินปลายทาง',cod_collected:'รับเงินปลายทางแล้ว',cancelled:'ยกเลิก',refunded:'คืนเงินแล้ว'};
const statuses={new:'เข้าใหม่ / รอตรวจ',ready:'พร้อมส่ง',shipped:'ส่งแล้ว',delivered:'ส่งสำเร็จ',cancelled:'ยกเลิก',returned:'ส่งคืน'};
const calls={new:'ยังไม่โทร',no_answer:'ไม่รับสาย',callback:'นัดโทรกลับ',interested:'สนใจ / รอตัดสินใจ',declined:'คงแพ็กเดิม',sold:'ตกลงซื้อเพิ่ม',do_not_call:'ไม่ต้องการให้โทรเสนอเพิ่ม'};
const deliveries={waiting_payment:'รอชำระเงิน',waiting_line:'รอลูกค้าแอด LINE',ready_to_send:'รอส่งลิงก์และโค้ด',sent:'ส่งทาง LINE แล้ว',in_parcel:'ใส่ใบ QR ในพัสดุ'};
const roles={owner:'เจ้าของ',telesales:'โทรและอัพเซลล์',finance:'การเงิน',fulfillment:'จัดส่ง'};
let firstLoad=true;
const financeSections=['finance-dashboard','finance','finance-cod','finance-report'];
let state,section='orders',view='all',page=0,batch,exportRequest,detailData,staff=[],loadVersion=0;
const owner=()=>state?.user.role==='owner',sales=()=>state?.sales_settings?.telesales_enabled===true&&['owner','telesales'].includes(state?.user.role),finance=()=>['owner','finance'].includes(state?.user.role),ship=()=>['owner','fulfillment'].includes(state?.user.role);
function message(s,error=false){const target=$('#detail').open?$('#detail-message'):$('#message');if(!target)return;target.textContent=s;target.hidden=!s;target.className=error?'inline-error':'inline-status';if(target.id==='message')target.classList.toggle('error',error);}
async function api(op,data={}){const r=await fetch('/api/book?op='+op,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});let d;try{d=await r.json();}catch{throw Error('เชื่อมต่อระบบไม่ได้ กรุณาลองใหม่');}if(!r.ok){if(r.status===401){$('#detail').close();$('#workspace').hidden=true;$('#login').hidden=false;$('#logout').hidden=true;}throw Error(d.error||'ทำรายการไม่สำเร็จ');}return d;}
async function task(button,fn){if(button)button.disabled=true;try{await fn();}catch(e){message(e.message,true);}finally{if(button)button.disabled=false;}}
function bind(selector,fn){$$(selector).forEach(b=>b.onclick=()=>task(b,()=>fn(b)));}
async function copy(s){await navigator.clipboard.writeText(s);message('📋 คัดลอกแล้ว');}
const ready=o=>o.status==='ready'&&!o.batch_id&&(o.payment_status==='paid'||o.method==='cod'&&o.payment_status==='cod_pending');
const badge=(s,kind='')=>`<span class="badge ${kind}">${esc(s)}</span>`;
const pbadge=s=>badge(payments[s]||s,['paid','cod_collected'].includes(s)?'green':['cancelled','refunded'].includes(s)?'red':'orange');
const button=(key,text,cls='')=>`<button data-book-action="${key}" class="${cls}">${text}</button>`;
async function navigate(next,filter='all'){section=next;view=filter;page=0;$('#search').value='';await load();window.scrollTo({top:0});}
function navigation(){
 const items=state.user.role==='finance'?[['finance-dashboard','📊 ยอดขาย'],['finance','💳 ตรวจเงิน'],['finance-cod','🚚 เงินปลายทาง'],['finance-report','📥 รายงาน']]:[...(sales()?[['calls','📞 งานโทร']]:[]),['orders','📦 ออเดอร์'],...(finance()?[['finance-dashboard','📊 ยอดขาย'],['finance','💳 ตรวจเงิน'],['finance-cod','🚚 เงินปลายทาง'],['finance-report','📥 รายงาน']]:[]),...(ship()?[['shipping','🚚 เตรียมส่ง'],['sent','✅ ส่งแล้ว']]:[]),...(sales()?[['delivery','💬 ส่ง KCUT']]:[]),...(owner()?[['settings','⚙️ ทีมและตั้งค่า']]:[])];
 $('#nav').innerHTML=items.map(([k,t])=>`<button data-nav="${k}" class="${section===k?'active':''}" ${section===k?'aria-current="page"':''}>${t}</button>`).join('');
 bind('[data-nav]',b=>navigate(b.dataset.nav,{calls:'calls',finance:'finance',shipping:'ready',sent:'shipped',delivery:'delivery'}[b.dataset.nav]||'all'));
 const titles={'finance-dashboard':['ยอดขายและเงินรับ 📊','แยกวันสั่งซื้อ วันรับเงิน และวันคืนเงิน'],'finance-cod':['เงินเก็บปลายทาง 🚚','ตรวจยอดที่ DHL นำส่งจริงก่อนยืนยันรับเงิน'],'finance-report':['รายงานบัญชี 📥','เลือกช่วงวันที่และดาวน์โหลด Excel'],overview:['ภาพรวมงาน 👋','เลือกงานที่ต้องทำ แล้วเริ่มดูแลลูกค้าได้เลย'],calls:['โทรหาลูกค้า 📞','รับงานก่อนโทร แล้วบันทึกผลหลังคุยเสร็จ'],orders:['ออเดอร์หนังสือ 🛒','ค้นหาและดูรายละเอียดลูกค้าได้จากที่เดียว'],finance:['ตรวจรับเงิน 💰','เช็กยอดเข้า TTB จริง ก่อนยืนยันรับเงิน'],sent:['ส่งสินค้าแล้ว ✅','ค้นหาเลขพัสดุและตรวจสถานะการจัดส่ง'],shipping:['เตรียมส่งหนังสือ 📦','ตรวจแพ็กและยอดเก็บปลายทางก่อนสร้างไฟล์'],delivery:['ส่งสิทธิ์ KCUT 💬','รับเงินแล้ว ให้ลูกค้าแอด LINE แล้วส่งลิงก์และโค้ด'],settings:['ทีมงานและตั้งค่า ⚙️','จัดการบัญชีและลิงก์ที่ทีมใช้งาน']};
 $('#page-title').textContent=titles[section][0];$('#page-description').textContent=titles[section][1];$('#greeting').textContent='สวัสดี '+state.user.name;
 $('#overview').hidden=section!=='orders';$('#list-panel').hidden=['overview','settings',...financeSections].includes(section);$('#finance-panel').hidden=!financeSections.includes(section);$('#shipping-panel').hidden=section!=='shipping';$('#settings-panel').hidden=section!=='settings';$('#range-label').hidden=section==='settings'||financeSections.includes(section);
}
function overview(){
 const m=state.summary,u=state.upsell;
 const cards=sales()&&!owner()?[['📞 รอโทร',m.calls,'รายการในความดูแล'],['🕒 ถึงเวลานัด',m.callbacks,'รายที่ต้องโทรกลับ'],['✨ ลูกค้าตกลงเพิ่ม',u.agreed,'บาท ตามรายการเพิ่มในช่วงเวลา'],['💰 ส่วนเพิ่มรับจริง',u.received,'บาท ตามวันที่ตรวจรับเงิน']]:[['🛒 ออเดอร์',m.orders,'รายการในช่วงเวลาที่เลือก'],['💳 รอตรวจเงิน',m.review,'รายการที่แนบสลิปแล้ว'],['📦 พร้อม Export',m.ready,'รายการยังไม่สร้างไฟล์'],['🚚 รอใส่เลขพัสดุ',m.exported,'Export แล้ว แต่ยังไม่บันทึกส่ง']];
 $('#metrics').innerHTML=cards.map(([label,value,note])=>`<div class="metric"><span>${label}</span><strong>${money(value)}</strong><small>${note}</small></div>`).join('');
 const links=[...(sales()?[['calls','unassigned','📥 รับงานใหม่','เลือกออเดอร์ที่ยังไม่มีคนดูแล'],['calls','callback','🕒 โทรตามนัด','ถึงเวลานัดโทรกลับแล้ว'],['delivery','delivery','💬 ส่งสิทธิ์ KCUT','รายการรับเงินแล้ว รอส่งทาง LINE']]:[]),...(finance()?[['finance','finance','💳 ตรวจสลิป','ตรวจเงินเข้าก่อนส่งสินค้า']]:[]),...(ship()?[['shipping','ready','📦 เตรียมส่งของ','พร้อมส่งและดาวน์โหลดไฟล์']]:[]),['orders','new','📥 ออเดอร์เข้าใหม่','ตรวจออเดอร์ก่อนเข้าคิวส่งของ']];
 $('#quick-actions').innerHTML=links.map(([s,v,t,n])=>`<button data-quick="${s}" data-view="${v}">${t}<span>${n}</span></button>`).join('');bind('[data-quick]',b=>navigate(b.dataset.quick,b.dataset.view));
 $('#team-panel').hidden=!sales()||!owner();$('#team-report').innerHTML=state.team.map(t=>`<div class="team-row"><div><strong>${esc(t.display_name||t.username||'เจ้าของ')}</strong><small>โทร ${money(t.calls)} ครั้ง</small></div><div><small>ตกลงเพิ่ม</small><strong>${money(t.agreed)} บาท</strong></div><div><small>ส่วนเพิ่มรับจริง</small><strong>${money(t.received)} บาท</strong></div></div>`).join('');
 if(owner())$('#team-report').insertAdjacentHTML('beforeend',`<p class="muted">ยอดเก็บปลายทางรอรับ ${money(m.pending_cod)} บาท • ยอดออเดอร์นับตามวันสั่ง • ยอดรับเงินจริงนับตามวันตรวจรับเงิน</p>`);
}
function draw(){
 const filters=section==='shipping'?[['ready','📦 พร้อม Export'],['exported','🚚 Export แล้ว / รอเลขพัสดุ']]:section==='sent'?[['shipped','ส่งแล้ว'],['delivered','ส่งสำเร็จ'],['returned','พัสดุส่งคืน']]:section==='calls'?[['calls','📞 งานที่ต้องโทร'],['unassigned','📥 ยังไม่มีผู้ดูแล'],['callback','🕒 ถึงเวลานัด'],['all','ทั้งหมดในความดูแล']]:section==='orders'?[['all','ทั้งหมด'],['new','เข้าใหม่'],['ready','พร้อม Export'],['exported','Export แล้ว'],['shipped','ส่งแล้ว'],['delivered','ส่งสำเร็จ'],['cancelled','ยกเลิก']]:[];
 $('#filters').innerHTML=filters.map(([v,t])=>`<button data-filter="${v}" class="${v===view?'active':''}">${t}</button>`).join('');bind('[data-filter]',async b=>{view=b.dataset.filter;page=0;await load();});
 $('#export-bar').hidden=section!=='shipping'||view!=='ready';$('#select-all').checked=false;$('#result-count').textContent=`พบ ${money(state.total)} รายการ • หน้าละ 50 รายการ`;
 $('#rows').innerHTML=state.orders.map(o=>{
 const unclaimed=state.user.role==='telesales'&&!o.assigned_to;
 return `<article class="order-card"><div><span class="muted">${num(o)} · ${date(o.created_at)}</span><h3>${esc(o.first_name)} ${esc(o.last_name)}</h3>${unclaimed?'<span class="muted">รับงานเพื่อดูเบอร์และรายละเอียด</span>':`<a class="phone" href="tel:${esc(o.phone)}">📞 ${esc(o.phone)}</a>`}<p class="muted">${esc(o.province)}</p></div><div><b>${o.package==='bundle'?'หนังสือ + เว็บ Prompt':'หนังสือ 1 เล่ม'}</b><p>${money(o.amount)} บาท · ${o.method==='cod'?'เก็บปลายทาง':'โอนเงิน'}</p>${pbadge(o.payment_status)}${(o.addons||[]).filter(a=>!['cancelled','refunded'].includes(a.payment_status)).map(a=>`<p class="small-text">＋ ${esc(products[a.product][0])} · ${payments[a.payment_status]}</p>`).join('')}</div><div>${badge(o.status==='ready'&&o.batch_id?'Export แล้ว / รอเลขพัสดุ':statuses[o.status],o.status==='ready'?'green':'')}${sales()?badge(calls[o.call_status]):''}${sales()?`<p class="muted">${o.assignee?'ผู้ดูแล '+esc(o.assignee):'ยังไม่มีผู้ดูแล'}</p>`:''}${sales()&&o.next_call_at?`<p class="muted">🕒 ${date(o.next_call_at)}</p>`:''}${o.tracking?`<p class="muted">เลขพัสดุ ${esc(o.tracking)}</p>`:''}${o.batch_id?'<p class="muted">ส่งออกไฟล์แล้ว</p>':''}</div><div>${section==='shipping'&&ready(o)?`<label class="check"><input class="choose" type="checkbox" value="${o.id}"> เลือกส่ง</label>`:''}${unclaimed?`<button data-claim="${o.id}" class="primary">รับงานนี้</button>`:`<button data-detail="${o.id}" class="primary">เปิดรายละเอียด →</button>`}</div></article>`;
 }).join('')||'<div class="empty"><p class="emoji">🌿</p><h3>ยังไม่มีรายการในหน้านี้</h3><p class="muted">ลองเปลี่ยนตัวกรอง ช่วงเวลา หรือคำค้นหา</p></div>';
 bind('[data-detail]',b=>detail(b.dataset.detail));bind('[data-claim]',async b=>{const o=state.orders.find(x=>x.id===b.dataset.claim);await api('sales_action',{id:o.id,revision:o.revision,action:'claim'});await load();await detail(o.id);message('รับงานแล้ว เริ่มโทรได้เลย');});
 $('#prev').disabled=page===0;$('#next').disabled=(page+1)*50>=state.total;$('#page-label').textContent=`${page+1} / ${Math.max(1,Math.ceil(state.total/50))}`;
}
async function load(){const version=++loadVersion;const next=await api('crm',{page,view,query:$('#search').value.trim(),days:Number($('#range').value)});if(version!==loadVersion)return;state=next;if(firstLoad){firstLoad=false;if(state.user.role==='finance')section='finance-dashboard';}$('#login').hidden=true;$('#workspace').hidden=false;$('#logout').hidden=false;$('#identity').textContent=state.user.name+' · '+roles[state.user.role];navigation();overview();draw();if(section==='settings')await settings();if(section==='shipping')await shipping();if(financeSections.includes(section))await bookFinance.render(section,api,detail);}
function callForm(o){return `<section class="detail-section"><h3>📞 บันทึกผลการโทร</h3><form id="call-form" class="form-grid"><label>ผลการโทร<select name="status" id="call-status">${Object.entries(calls).filter(([k])=>k!=='new').map(([k,v])=>`<option value="${k}" ${o.call_status===k?'selected':''}>${v}</option>`).join('')}</select></label><label id="callback-label" ${o.call_status==='callback'?'':'hidden'}>วันและเวลานัด (เวลาไทย)<input id="callback-at" name="next_call_at" type="datetime-local" value="${o.next_call_at?new Date(new Date(o.next_call_at).getTime()+7*3600000).toISOString().slice(0,16):''}"></label><label class="wide">หมายเหตุการคุย<textarea name="note" maxlength="1000" placeholder="เช่น ลูกค้าสะดวกช่วงเย็น">${esc(o.call_note)}</textarea></label><button class="primary" type="submit">💾 บันทึกผล</button><button type="submit" name="next" value="yes">บันทึกและเปิดคนถัดไป →</button></form><details><summary>💡 บทพูดเสนอเว็บ Prompt</summary><p>โทรมายืนยันออเดอร์หนังสือค่ะ เพิ่ม 145 บาทจะได้เว็บรวม Prompt ในหนังสือ สำหรับเปิดคัดลอกไปใช้ได้สะดวก รวมเป็น 490 บาท ส่งฟรี สนใจเพิ่มไหมคะ</p><p class="muted">คลิปสอนฟรีเป็นของที่ให้พร้อมหนังสืออยู่แล้ว ส่วนเพิ่ม 145 บาทคือเว็บ Prompt</p></details></section>`;}
function offers(o,addons){
 const active=addons.filter(a=>!['cancelled','refunded'].includes(a.payment_status));
 return `<section class="detail-section"><h3>✨ ลูกค้าตกลงซื้อเพิ่ม</h3><p class="muted">เลือกหลังลูกค้ายืนยันแล้ว ราคา KCUT เป็นยอดเพิ่มจากหนังสือ และชำระด้วยการโอน</p><div class="offer-grid">${Object.entries(products).map(([p,[title,price]])=>{
 const disabled=p==='prompt_upgrade'?(o.package!=='book'||o.batch_id||!['new','ready'].includes(o.status)||active.some(a=>a.product===p)||(o.method==='transfer'&&o.payment_status!=='paid')):active.some(a=>a.product.startsWith('kcut_'));
 return `<button class="offer" data-offer="${p}" ${disabled?'disabled':''}>${esc(title)}<strong>＋ ${money(price)} บาท</strong><span>${p==='prompt_upgrade'?'รวมหนังสือเป็น 490 บาท':'ส่งลิงก์และโค้ดทาง LINE หลังตรวจรับเงิน'}</span></button>`;}).join('')}</div><p class="muted">เว็บ Prompt เพิ่มได้ก่อนส่งออกสินค้า • รายการโอนต้องตรวจรับยอดหนังสือก่อน • KCUT เลือกได้หนึ่งแพ็กต่อออเดอร์</p></section>`;
}
function addonCard(a){let actions='';
 if(a.method==='transfer'&&['awaiting_slip','review'].includes(a.payment_status)&&!['cancelled','returned'].includes(detailData.order.status)){
  actions+=`<button data-pay-link="${a.id}">🔗 คัดลอกลิงก์ชำระ ${money(a.amount)} บาท</button>`;
  if(sales()||finance())actions+=`<label>📎 แนบสลิปที่ลูกค้าส่งให้<input data-upload="${a.id}" type="file" accept="image/jpeg,image/png,image/webp"></label>`;
 }
 if(finance()&&a.payment_status==='review')actions+=`<button data-addon-slip="${a.id}">🔎 เปิดสลิป</button><button class="primary" data-addon-action="paid" data-id="${a.id}">ตรวจยอดเข้าแล้ว ยืนยัน ${money(a.amount)} บาท</button><button data-addon-action="reject" data-id="${a.id}">ให้แนบสลิปใหม่</button>`;
 if(sales()&&['awaiting_slip','review','cod_pending'].includes(a.payment_status))actions+=`<button class="danger" data-addon-action="cancel" data-id="${a.id}">ยกเลิกรายการเพิ่ม</button>`;
 if(finance()&&a.payment_status==='paid'&&a.method==='transfer')actions+=`<button class="danger" data-addon-refund="${a.id}">บันทึกคืนเงินรายการนี้</button>`;
 let delivery='';if(sales()&&a.product!=='prompt_upgrade'&&a.payment_status==='paid')delivery=`<form class="delivery-form form-grid" data-id="${a.id}"><label>ชื่อ / ID LINE ของลูกค้า<input name="line_name" value="${esc(a.line_name)}" maxlength="150" ${a.delivery_status==='sent'?'readonly':''}></label><label>โค้ดสำหรับลูกค้ารายนี้<input name="code" value="${esc(a.activation_code)}" maxlength="500" autocomplete="off" ${a.delivery_status==='sent'?'readonly':''}></label><label>ขั้นตอนส่งสิทธิ์<select name="status" ${a.delivery_status==='sent'?'disabled':''}>${['waiting_line','ready_to_send','sent'].map(k=>`<option value="${k}" ${a.delivery_status===k?'selected':''}>${deliveries[k]}</option>`).join('')}</select></label><label>หมายเหตุ<input name="note" value="${esc(a.delivery_note)}" maxlength="1000" ${a.delivery_status==='sent'?'readonly':''}></label>${a.delivery_status!=='sent'?'<button class="primary" type="submit">💾 บันทึกขั้นตอนส่งสิทธิ์</button>':''}<button type="button" data-delivery-copy="${a.id}">📋 คัดลอกข้อความส่ง LINE</button></form><p class="muted">คัดลอกข้อความแล้วนำไปส่ง LINE เอง จากนั้นเลือก “ส่งทาง LINE แล้ว”</p>`;
 return `<article class="addon-card"><h3>${esc(products[a.product][0])} · ${money(a.amount)} บาท</h3>${pbadge(a.payment_status)}${badge(deliveries[a.delivery_status])}<div class="actions">${actions}</div>${delivery}</article>`;
}
async function detail(id){detailData=await api('crm_detail',{id});const {order:o,addons,audit}=detailData;const canSales=sales()&&(owner()||o.assigned_to===state.user.id),closed=['cancelled','returned'].includes(o.status);let actions='';
 if(o.method==='cod'&&o.status==='new'&&ship())actions+=button('ready','✅ ยืนยันออเดอร์พร้อมส่ง','primary');
 if(o.method==='transfer'&&o.payment_status==='review'&&o.status==='new'&&finance())actions+=`<button id="view-slip">🔎 เปิดสลิปหนังสือ</button>${button('paid','ตรวจยอดเข้าแล้ว ยืนยันรับเงิน','primary')}${button('reject_slip','ให้แนบสลิปใหม่')}`;
 if(o.status==='ready'&&o.batch_id&&ship())actions+=`<label>เลขพัสดุ DHL<input id="tracking" minlength="5" maxlength="60" placeholder="เลขพัสดุจริง"></label>${button('shipped','บันทึกว่าจัดส่งแล้ว','primary')}`;
 if(o.status==='shipped'&&ship())actions+=button('delivered','✅ ยืนยันส่งสำเร็จ','primary');
 if(o.status==='delivered'&&o.method==='cod'&&o.payment_status==='cod_pending'&&finance())actions+=button('cod_collected','ตรวจยอด DHL แล้ว ยืนยันรับเงิน','primary');
 if(['shipped','delivered'].includes(o.status)&&ship())actions+=button('returned','บันทึกพัสดุส่งคืน');
 if(['new','ready'].includes(o.status)&&!o.batch_id&&ship())actions+=button('cancelled','ยกเลิกออเดอร์','danger');
 if(closed&&['paid','cod_collected'].includes(o.payment_status)&&finance())actions+=button('refunded',`คืนค่าหนังสือ ${money(o.method==='cod'?o.amount:o.base_amount)} บาทแล้ว บันทึกคืนเงิน`);
 if(sales()&&owner()&&!staff.length)staff=await api('staff_list');
 $('#detail-body').innerHTML=`<div id="detail-message" role="status" hidden></div><div class="customer-head"><div><p class="eyebrow">${num(o)} · ${date(o.created_at)}</p><h2>${esc(o.first_name)} ${esc(o.last_name)}</h2><a href="tel:${esc(o.phone)}" class="phone">📞 ${esc(o.phone)}</a><div class="actions"><button id="copy-phone">📋 คัดลอกเบอร์</button></div></div><div>${badge(o.package==='bundle'?'หนังสือ + เว็บ Prompt':'หนังสือ 1 เล่ม')}<p class="result-total">${money(o.amount)} บาท · ${o.method==='cod'?'เก็บปลายทาง':'โอนเงิน'}</p>${pbadge(o.payment_status)}${badge(statuses[o.status])}</div></div>
 ${sales()&&owner()?`<form id="assign-form" class="form-grid"><label>👤 ผู้ดูแล<select name="user_id"><option value="">ยังไม่มอบหมาย</option>${staff.filter(s=>s.active&&['owner','telesales'].includes(s.role)).map(s=>`<option value="${s.user_id}" ${s.user_id===o.assigned_to?'selected':''}>${esc(s.display_name||s.username||s.email)}</option>`).join('')}</select></label><button type="submit">บันทึกผู้ดูแล</button></form>`:''}
 ${canSales&&!closed?callForm(o):''}${canSales&&!closed&&o.call_status!=='do_not_call'?offers(o,addons):''}
 ${sales()||addons.length?`<section class="detail-section"><h3>🧾 รายการซื้อเพิ่ม ${addons.length?`(${addons.length})`:''}</h3>${addons.map(addonCard).join('')||'<p class="muted">ยังไม่มีรายการซื้อเพิ่ม</p>'}</section>`:''}<section class="detail-section"><h3>📦 ข้อมูลหนังสือและจัดส่ง</h3>${o.payment_note?`<p class="notice">หมายเหตุการเงิน: ${esc(o.payment_note)}</p>`:''}<p class="preline">${esc(`${o.first_name} ${o.last_name}\n${o.address}\n${o.subdistrict} ${o.district} ${o.province} ${o.postcode}\nหมายเหตุลูกค้า: ${o.note||'-'}`)}</p>${o.tracking?`<p>เลขพัสดุ: <b>${esc(o.tracking)}</b></p>`:''}${o.package==='bundle'?'<div class="notice">📄 ใส่ใบ QR และวิธีใช้เว็บ Prompt ในกล่องด้วย</div>':''}<div class="actions">${actions}</div>${ship()&&!o.batch_id&&['new','ready'].includes(o.status)?`<details><summary>✏️ แก้ชื่อ เบอร์ หรือที่อยู่</summary><form id="edit-order" class="form-grid">${[['first_name','ชื่อ'],['last_name','นามสกุล'],['phone','เบอร์โทร'],['address','ที่อยู่'],['subdistrict','ตำบล / แขวง'],['district','อำเภอ / เขต'],['province','จังหวัด'],['postcode','รหัสไปรษณีย์'],['note','หมายเหตุ']].map(([k,l])=>`<label>${l}<input name="${k}" value="${esc(o[k])}" ${k==='note'?'':'required'} maxlength="${k==='address'||k==='note'?500:100}"></label>`).join('')}<button type="submit" class="primary">บันทึกข้อมูล</button></form></details>`:''}</section><details><summary>🕘 ประวัติการดูแลลูกค้า</summary>${audit.map(a=>`<div class="audit-row">${date(a.created_at)} · ${esc(a.actor_name)}<br>${esc(auditLabel(a))}${a.details?.note?'<br>'+esc(a.details.note):''}</div>`).join('')||'<p>ยังไม่มีประวัติ</p>'}</details>`;
 if(!$('#detail').open)$('#detail').showModal();$('#copy-phone').onclick=()=>task($('#copy-phone'),()=>copy(o.phone));
 async function refresh(note){await load();await detail(o.id);message(note||'✅ บันทึกแล้ว');}
 if($('#assign-form'))$('#assign-form').onsubmit=e=>{e.preventDefault();task(e.submitter,async()=>{await api('sales_action',{id:o.id,revision:o.revision,action:'assign',data:Object.fromEntries(new FormData(e.target))});await refresh();});};
 if($('#call-form')){
  $('#call-status').onchange=()=>{$('#callback-label').hidden=$('#call-status').value!=='callback';$('#callback-at').required=$('#call-status').value==='callback';};$('#call-status').onchange();
  $('#call-form').onsubmit=e=>{e.preventDefault();task(e.submitter,async()=>{const data=Object.fromEntries(new FormData(e.target));data.next_call_at=data.status==='callback'&&data.next_call_at?new Date(data.next_call_at+':00+07:00').toISOString():null;await api('sales_action',{id:o.id,revision:o.revision,action:'call',data});if(e.submitter.name==='next'){await load();const next=state.orders.find(x=>x.id!==o.id&&x.assigned_to===state.user.id&&!['sold','declined','do_not_call','callback'].includes(x.call_status));if(next)await detail(next.id);else{$('#detail').close();message('บันทึกแล้ว ไม่มีคนถัดไปในคิวหน้านี้');}}else await refresh();});};
 }
 bind('[data-offer]',async b=>{const p=b.dataset.offer,[title,amount]=products[p];if(!confirm(`ลูกค้ายืนยันซื้อ ${title} เพิ่ม ${money(amount)} บาทแล้วใช่ไหม?${p==='prompt_upgrade'&&o.method==='cod'?' ยอดเก็บปลายทางจะเป็น 490 บาท':''}`))return;await api('sales_action',{id:o.id,revision:o.revision,action:'addon',data:{id:crypto.randomUUID(),product:p}});await refresh('เพิ่มรายการแล้ว ตรวจสถานะชำระเงินด้านล่าง');});
 bind('[data-book-action]',async b=>{let note='';if(['reject_slip','refunded'].includes(b.dataset.bookAction)){note=prompt(b.dataset.bookAction==='refunded'?'เหตุผลคืนเงิน (บันทึกหลังคืนเงินจริงแล้วเท่านั้น)':'เหตุผลที่ให้ลูกค้าแนบสลิปใหม่');if(note===null)return;if(note.trim().length<3)throw Error('กรอกเหตุผลอย่างน้อย 3 ตัวอักษร');}if(!confirm(`${b.textContent} สำหรับ ${num(o)}?`))return;await api('change',{id:o.id,revision:o.revision,action:b.dataset.bookAction,data:{tracking:$('#tracking')?.value,note}});await refresh();});
 if($('#view-slip'))$('#view-slip').onclick=()=>task($('#view-slip'),()=>slipView('slip_view',o.id));
 if($('#edit-order'))$('#edit-order').onsubmit=e=>{e.preventDefault();task(e.submitter,async()=>{await api('change',{id:o.id,revision:o.revision,action:'edit',data:Object.fromEntries(new FormData(e.target))});await refresh();});};
 bind('[data-pay-link]',async b=>copy((await api('addon_link',{id:b.dataset.payLink})).url));bind('[data-addon-slip]',b=>slipView('addon_slip_view',b.dataset.addonSlip));
 bind('[data-addon-action]',async b=>{const a=addons.find(x=>x.id===b.dataset.id);if(!confirm(`${b.textContent} สำหรับ ${products[a.product][0]} ${money(a.amount)} บาท?`))return;await api('addon_action',{id:a.id,revision:a.revision,action:b.dataset.addonAction});await refresh();});
 bind('[data-addon-refund]',async b=>{const a=addons.find(x=>x.id===b.dataset.addonRefund);const note=prompt(`กรอกเหตุผลคืนเงิน ${money(a.amount)} บาท และผลการยกเลิกสิทธิ์ (บันทึกหลังคืนเงินจริงแล้วเท่านั้น)`);if(note===null)return;if(!confirm(`คืนเงินจริง ${money(a.amount)} บาทแล้ว และตรวจการยกเลิกสิทธิ์เรียบร้อย?`))return;await api('addon_action',{id:a.id,revision:a.revision,action:'refunded',data:{note}});await refresh();});
 $$('[data-upload]').forEach(input=>input.onchange=()=>task(input,async()=>{const image=await fileImage(input.files[0]);await api('addon_staff_slip',{id:input.dataset.upload,image});await refresh('แนบสลิปแล้ว รอฝ่ายการเงินตรวจยอด');}));
 $$('.delivery-form').forEach(form=>form.onsubmit=e=>{e.preventDefault();task(e.submitter,async()=>{const data=Object.fromEntries(new FormData(form)),a=addons.find(x=>x.id===form.dataset.id);if(data.status==='sent'&&!confirm('ส่งลิงก์และโค้ดให้ลูกค้าทาง LINE เรียบร้อยแล้วใช่ไหม?'))return;await api('addon_action',{id:a.id,revision:a.revision,action:'delivery',data});await refresh();});});
 bind('[data-delivery-copy]',async b=>{const a=addons.find(x=>x.id===b.dataset.deliveryCopy),f=b.closest('form'),code=f.elements.code.value.trim(),s=state.sales_settings;if(!s.kcut_url||!s.kcut_guide_url)throw Error('ให้อ๊อฟใส่ลิงก์เข้าใช้และวิธีใช้ในเมนูทีมและตั้งค่าก่อน');if(!code)throw Error('กรอกโค้ดสำหรับลูกค้ารายนี้ก่อน');await copy(`สิทธิ์ ${products[a.product][0]} ของคุณพร้อมใช้งานแล้วค่ะ\n\nเข้าใช้งาน: ${s.kcut_url}\nวิธีใช้งาน: ${s.kcut_guide_url}\nโค้ด: ${code}\n\nอ้างอิงออเดอร์ ${num(o)}`);});
}
function auditLabel(a){const labels={sales_claim:'รับงานโทร',sales_assign:'เปลี่ยนผู้ดูแล',sales_call:'บันทึกผลโทร: '+(calls[a.details?.status]||''),sales_addon:'เพิ่มสินค้า: '+(products[a.details?.product]?.[0]||''),addon_paid:'ตรวจรับเงินส่วนเพิ่ม',addon_reject:'ให้แนบสลิปส่วนเพิ่มใหม่',addon_cancel:'ยกเลิกสินค้าเพิ่ม',addon_delivery:'บันทึกการส่งสิทธิ์: '+(deliveries[a.details?.delivery_status]||''),addon_slip_uploaded:'แนบสลิปส่วนเพิ่ม',view_addon_slip:'เปิดสลิปส่วนเพิ่ม',view_slip:'เปิดสลิปหนังสือ',paid:'ตรวจรับเงินหนังสือ',ready:'ยืนยันพร้อมส่ง',shipped:'บันทึกส่งสินค้า',delivered:'ส่งสำเร็จ',cod_collected:'ตรวจรับเงิน DHL',cancelled:'ยกเลิกออเดอร์',refunded:'บันทึกคืนเงิน',returned:'พัสดุส่งคืน',edit:'แก้ข้อมูลจัดส่ง',slip_uploaded:'ลูกค้าแนบสลิป',reject_slip:'ให้แนบสลิปหนังสือใหม่'};return labels[a.action]||a.action;}
async function slipView(op,id){const d=await api(op,{id});$('#slip-image').src=d.url;$('#slip-dialog').showModal();}
async function fileImage(file){if(!file)throw Error('เลือกรูปสลิปก่อน');if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5242880)throw Error('ใช้ JPG, PNG หรือ WebP ขนาดไม่เกิน 5 MB');return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(Error('อ่านไฟล์ไม่ได้'));r.readAsDataURL(file);});}
async function settings(){$('#sales-links-panel').hidden=!sales();$('#tracking-settings').hidden=!sales();$('#analytics-panel').hidden=!sales();$('#paused-notice').hidden=sales();$('#staff-sales-option').disabled=!sales();staff=await api('staff_list');$('#staff').innerHTML=staff.map(s=>`<div class="staff-row"><div><b>${esc(s.display_name||s.email)}</b><br><small>${esc(s.username||s.email)} · ${roles[s.role]} · ${s.active?'ใช้งานได้':'ปิดบัญชีแล้ว'}</small></div>${s.role!=='owner'&&s.active?`<button class="danger" data-disable="${s.user_id}">ปิดบัญชีนี้</button>`:''}</div>`).join('');bind('[data-disable]',async b=>{if(confirm('ปิดบัญชีนี้ พนักงานจะเข้าใช้งานต่อไม่ได้?')){await api('staff_disable',{id:b.dataset.disable});await settings();message('ปิดบัญชีแล้ว');}});for(const k of ['line_url','kcut_url','kcut_guide_url'])$('#sales-settings').elements[k].value=state.sales_settings[k];const analytics=(await api('admin',{page:0})).metrics;const eventNames={page_view:'เปิดหน้าเว็บ',checkout_start:'เริ่มสั่งซื้อ',order_submitted:'ส่งคำสั่งซื้อ'};$('#site-analytics').innerHTML='<p class=muted>30 วันล่าสุด เฉพาะผู้ชมที่ยินยอมเก็บสถิติ</p><div class=metrics>'+Object.entries(eventNames).map(([k,v])=>{const e=analytics.events.find(x=>x.event===k);return `<div class=metric><span>${v}</span><strong>${money(e?.visitors)}</strong><small>เซสชัน</small></div>`}).join('')+`<div class=metric><span>เวลาอ่านเฉลี่ย</span><strong>${money(analytics.engagement)}</strong><small>วินาทีต่อช่วงการอ่าน</small></div></div>`;const conf=await fetch('/api/book?op=config').then(r=>r.json());for(const k of ['ga4_id','pixel_id','clarity_id'])$('#tracking-form').elements[k].value=conf[k]||'';}
async function shipping(){const batches=await api('batches');$('#batches').innerHTML=batches.map(b=>`<div class="batch-row"><span>${date(b.created_at)} · ${b.id.slice(0,8)}<br><small>${money(b.count)} ออเดอร์ · โดย ${esc(b.created_by)}</small></span><button data-batch="${b.id}">เปิดรอบ / ดาวน์โหลดซ้ำ</button></div>`).join('')||'<p class="muted">ยังไม่มีรอบส่งออก</p>';bind('[data-batch]',async b=>showBatch(await api('batch',{id:b.dataset.batch})));}
function showBatch(b){batch=b;const books=b.orders.filter(o=>o.package==='book').length,bundles=b.orders.length-books;$('#batch-summary').innerHTML=`<p><b>📘 หนังสืออย่างเดียว ${books} ชุด · 📘 + 📄 เว็บ Prompt ${bundles} ชุด</b></p><p>เตรียมหนังสือ ${b.orders.length} เล่ม และใบ QR เว็บ Prompt ${bundles} ใบ</p><p>ยอดเก็บปลายทางรวม <b>${money(b.orders.reduce((sum,o)=>sum+(o.method==='cod'&&o.payment_status==='cod_pending'?o.amount:0),0))} บาท</b></p><p class="muted">สร้างไฟล์แล้ว ยังไม่ถือว่าส่งสินค้า กรุณาใส่เลขพัสดุหลังจัดส่ง</p>`;$('#download-panel').hidden=false;$('#batch-label').textContent=`รอบ ${b.id.slice(0,8)} · ${b.orders.length} รายการ`;$('#download-panel').scrollIntoView({block:'center'});}
function printDoc(html){const w=window.open('','_blank');if(!w)throw Error('อนุญาตหน้าต่างใหม่เพื่อพิมพ์');w.document.write(`<!doctype html><html lang="th"><meta charset="utf-8"><title>ใบแพ็กหนังสือ</title><link rel="stylesheet" href="/book-assets/print.css"><button id="print-now">พิมพ์ / บันทึก PDF</button>${html}</html>`);w.document.close();w.document.getElementById('print-now').addEventListener('click',()=>w.print());}
$('#login').onsubmit=e=>{e.preventDefault();task(e.submitter,async()=>{await api('login',Object.fromEntries(new FormData(e.target)));e.target.reset();await load();});};
$('#logout').onclick=()=>task($('#logout'),async()=>{await api('logout');location.reload();});
$('#range').onchange=()=>task($('#range'),async()=>{page=0;await load();});$('#search-form').onsubmit=e=>{e.preventDefault();task(e.submitter,async()=>{page=0;await load();});};$('#reload').onclick=()=>task($('#reload'),load);$('#prev').onclick=()=>task($('#prev'),async()=>{page--;await load();});$('#next').onclick=()=>task($('#next'),async()=>{page++;await load();});
$('#select-all').onchange=e=>$$('.choose').forEach(x=>x.checked=e.target.checked);
$('#export').onclick=()=>task($('#export'),async()=>{const ids=$$('.choose:checked').map(x=>x.value).sort();if(!ids.length)throw Error('เลือกรายการพร้อมส่งก่อน');if(!confirm(`สร้างไฟล์ส่งของ ${ids.length} รายการ? รายการเหล่านี้จะย้ายไปแท็บ Export แล้ว / รอเลขพัสดุ`))return;const signature=ids.join(',');if(!exportRequest||exportRequest.signature!==signature)exportRequest={signature,id:crypto.randomUUID()};const b=await api('export',{id:exportRequest.id,ids});exportRequest=null;await load();showBatch(b);message('สร้างรอบแล้ว ดาวน์โหลดไฟล์ได้ด้านล่าง');});
$('#packing-xlsx').onclick=()=>bookExport.download(bookExport.xlsx(batch.orders,'packing'),`รายการแพ็กของ-${batch.id.slice(0,8)}.xlsx`);
$('#xlsx').onclick=()=>bookExport.download(bookExport.xlsx(batch.orders),`DHL-book-${batch.id.slice(0,8)}.xlsx`);$('#csv').onclick=()=>bookExport.download(bookExport.csv(batch.orders),`DHL-book-${batch.id.slice(0,8)}.csv`);
$('#packing').onclick=()=>task($('#packing'),async()=>printDoc(batch.orders.map(o=>`<div class="card"><h2>${num(o)}</h2><b>${esc(o.first_name)} ${esc(o.last_name)}</b><p>${esc(o.phone)}<br>${esc(o.address)}<br>${esc(o.subdistrict)} ${esc(o.district)} ${esc(o.province)} ${esc(o.postcode)}</p><b>□ หนังสือ 1 เล่ม ${o.package==='bundle'?' • □ ใบ QR และวิธีใช้เว็บ Prompt':''}</b><p>สินค้าที่สั่ง: ${o.package==='bundle'?'หนังสือ + เว็บ Prompt':'หนังสือ 1 เล่ม'}<br>ยอดออเดอร์ ${o.amount} บาท · ${o.method==='cod'?'เก็บปลายทาง':'โอนเงิน'}<br>สถานะเงิน: ${esc(payments[o.payment_status])}<br>เก็บปลายทาง ${o.method==='cod'&&o.payment_status==='cod_pending'?o.amount:0} บาท<br>หมายเหตุ: ${esc(o.note)}</p></div>`).join('')));
$('#print-insert').onclick=()=>task($('#print-insert'),async()=>{const d=await api('insert');printDoc(`<div class="card"><h2>เว็บรวม Prompt ในหนังสือ</h2><img src="/book-assets/prompt-qr.svg" alt="QR เข้าเว็บ Prompt"><p>businessboy.ai/promptbook<br>รหัสเข้าเว็บ: <b>${esc(d.code)}</b></p><ol><li>เปิดกล้องมือถือ สแกน QR</li><li>แตะลิงก์และกรอกรหัส</li><li>เลือกเรื่องแล้วกดคัดลอก Prompt</li><li>วางในเครื่องมือ AI แล้วปรับให้ตรงงาน</li></ol></div>`);});
for(const [id,op] of [['staff-form','staff_create'],['sales-settings','sales_settings'],['tracking-form','settings']])$('#'+id).onsubmit=e=>{e.preventDefault();task(e.submitter,async()=>{await api(op,Object.fromEntries(new FormData(e.target)));if(id==='staff-form')e.target.reset();await load();message('✅ บันทึกแล้ว');});};
$('#close-detail').onclick=()=>$('#detail').close();$('#close-slip').onclick=()=>{$('#slip-dialog').close();$('#slip-image').removeAttribute('src');};
const setFont=large=>{document.body.classList.toggle('large-text',large);$('#font-size').setAttribute('aria-pressed',String(large));$('#font-size').textContent=large?'ก ขนาดปกติ':'ก ตัวใหญ่';};try{setFont(localStorage.getItem('book_admin_large')==='1');}catch{}
$('#font-size').onclick=()=>{const large=!document.body.classList.contains('large-text');setFont(large);try{localStorage.setItem('book_admin_large',large?'1':'0');}catch{}};
load().catch(e=>{if(!/เข้าสู่ระบบ/.test(e.message))message(e.message,true);});
})();
