// XLSX with explicit text cell types preserves Thai text, leading zeroes and prevents formula execution.
(() => {
const enc=new TextEncoder(),xml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c])).replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g,'');
const headers=['Order Reference','Recipient Name','Recipient Phone','Address','Subdistrict','District','Province','Postcode','Country','COD Amount THB','Order Amount THB','Package','Quantity','Packing Note','Customer Note','Payment Method','Payment Status'];
const packingHeaders=['เลขออเดอร์','ชื่อผู้รับ','เบอร์โทร','ที่อยู่','ตำบล / แขวง','อำเภอ / เขต','จังหวัด','รหัสไปรษณีย์','ประเทศ','ยอดเก็บปลายทาง (บาท)','ยอดออเดอร์ (บาท)','สินค้าที่สั่ง','จำนวนหนังสือ (เล่ม)','รายการที่ต้องแพ็ก','หมายเหตุลูกค้า','วิธีชำระเงิน','สถานะชำระเงิน'];
const paymentLabels={paid:'รับเงินแล้ว',cod_pending:'รอรับเงินปลายทาง',cod_collected:'รับเงินปลายทางแล้ว',review:'รอตรวจสลิป',awaiting_slip:'รอโอนเงิน',refunded:'คืนเงินแล้ว',cancelled:'ยกเลิก'};
function rows(orders,mode='carrier'){return [mode==='packing'?packingHeaders:headers,...orders.map(o=>[`BB${String(o.number).padStart(6,'0')}`,`${o.first_name} ${o.last_name}`,o.phone,o.address,o.subdistrict,o.district,o.province,o.postcode,'TH',o.method==='cod'&&o.payment_status==='cod_pending'?o.amount:0,o.amount,o.package==='bundle'?'หนังสือ 1 เล่ม + เว็บ Prompt':'หนังสือ 1 เล่ม',1,o.package==='bundle'?'หนังสือ 1 เล่ม + ใบ QR เข้าเว็บ Prompt พร้อมวิธีใช้':'หนังสือ 1 เล่ม',o.note,o.method==='cod'?'เก็บเงินปลายทาง':'โอนเงิน',paymentLabels[o.payment_status]||o.payment_status])];}
function crc32(b){let c=0xffffffff;for(const v of b){c^=v;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
function zip(files){const parts=[],central=[];let offset=0;for(const [name,text] of Object.entries(files)){const n=enc.encode(name),b=enc.encode(text),crc=crc32(b);const h=new Uint8Array(30+n.length),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint32(14,crc,true);v.setUint32(18,b.length,true);v.setUint32(22,b.length,true);v.setUint16(26,n.length,true);h.set(n,30);parts.push(h,b);const c=new Uint8Array(46+n.length),d=new DataView(c.buffer);d.setUint32(0,0x02014b50,true);d.setUint16(4,20,true);d.setUint16(6,20,true);d.setUint16(8,0x800,true);d.setUint32(16,crc,true);d.setUint32(20,b.length,true);d.setUint32(24,b.length,true);d.setUint16(28,n.length,true);d.setUint32(42,offset,true);c.set(n,46);central.push(c);offset+=h.length+b.length;}const length=central.reduce((s,b)=>s+b.length,0),end=new Uint8Array(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,central.length,true);v.setUint16(10,central.length,true);v.setUint32(12,length,true);v.setUint32(16,offset,true);return new Blob([...parts,...central,end],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});}
function xlsx(orders,mode='carrier'){const data=rows(orders,mode),sheet=`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols><col min="1" max="17" width="24" customWidth="1"/></cols><sheetData>${data.map((row,i)=>`<row r="${i+1}">${row.map((cell,j)=>`<c r="${String.fromCharCode(65+j)}${i+1}" ${typeof cell==='number'?'t="n"':'t="inlineStr"'}>${typeof cell==='number'?`<v>${cell}</v>`:`<is><t xml:space="preserve">${xml(cell)}</t></is>`}</c>`).join('')}</row>`).join('')}</sheetData><autoFilter ref="A1:Q${data.length}"/></worksheet>`;return zip({'[Content_Types].xml':'<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>','_rels/.rels':'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>','xl/workbook.xml':'<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="DHL Orders" sheetId="1" r:id="rId1"/></sheets></workbook>','xl/_rels/workbook.xml.rels':'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>','xl/worksheets/sheet1.xml':sheet});}
function csv(orders){const safe=v=>{let s=String(v??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'};return new Blob(['\uFEFF'+rows(orders).map(row=>row.map(safe).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});}
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
window.bookExport={rows,xlsx,csv,download};
})();
