(() => {
'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>Number(n||0).toLocaleString('th-TH'),date=s=>s?new Date(s).toLocaleString('th-TH',{timeZone:'Asia/Bangkok',dateStyle:'short',timeStyle:'short'}):'-';
const today=()=>new Date(Date.now()+7*3600000).toISOString().slice(0,10);
let from=today().slice(0,7)+'-01',to=today(),preset='month',basis='ordered',filter='all',page=0,current='',generation=0;
const payment={paid:'รับเงินแล้ว',cod_collected:'รับเงิน DHL แล้ว',refunded:'คืนเงินแล้ว',review:'รอตรวจสลิป',awaiting_slip:'รอโอนเงิน',cod_pending:'รอรับเงินปลายทาง',cancelled:'ยกเลิก'};
const shipping={new:'เข้าใหม่',ready:'พร้อมส่ง',shipped:'ส่งแล้ว',delivered:'ส่งสำเร็จ',cancelled:'ยกเลิก',returned:'ส่งคืน'};
async function render(section,api,detail){
 const version=++generation;if(current!==section){page=0;current=section;}
 const queue=section==='finance'||section==='finance-cod';
 const params={from:queue?null:from||null,to:queue?null:to||null,basis:queue?'ordered':basis,view:section==='finance'?'review':section==='finance-cod'?'cod':filter,page};
 const data=await api('finance_report',params);if(version!==generation)return;
 const s=data.summary,net=s.transfer_received+s.cod_received-s.refunded;
 const cards=[['🛒 ยอดสั่งซื้อ',s.ordered,'ตามวันสั่ง ไม่รวมยกเลิก / ส่งคืน'],['💵 รับเงินโอนแล้ว',s.transfer_received,'ตามวันที่ยืนยันรับเงิน'],['🚚 รับเงิน DHL แล้ว',s.cod_received,'ตามวันที่ยืนยันรับเงิน'],['↩️ คืนเงินแล้ว',s.refunded,'ตามวันที่บันทึกคืนเงิน'],['💰 รับสุทธิ',net,'เงินรับในช่วงนี้ หักคืนเงินในช่วงนี้'],['💳 สลิปรอตรวจ',s.review,'ยอดค้างทั้งหมด ทุกวันที่'],['📦 ปลายทางรอรับ',s.pending_cod,'ยอดค้างทั้งหมด ทุกวันที่']];
 $('#finance-panel').innerHTML=`${queue?'<p class="notice">แสดงรายการค้างทั้งหมด เพื่อไม่ให้ตกหล่นจากการเลือกช่วงวันที่</p>':`<form id="finance-dates" class="panel form-grid"><label>📅 ช่วงเวลา<select name="preset"><option value="today" ${preset==='today'?'selected':''}>วันนี้</option><option value="month" ${preset==='month'?'selected':''}>เดือนนี้</option><option value="all" ${preset==='all'?'selected':''}>ทั้งหมด</option><option value="custom" ${preset==='custom'?'selected':''}>กำหนดเอง</option></select></label><button class="primary" type="submit">ดูข้อมูล</button><details class="wide" id="finance-advanced"><summary>ช่วงวันที่ / เลือกประเภทรายงาน</summary><div class="form-grid"><label>ตั้งแต่วันที่<input name="from" type="date" value="${from}"></label><label>ถึงวันที่<input name="to" type="date" value="${to}"></label><label>วันที่สำหรับรายการและ Excel<select name="basis">${[['ordered','วันที่สั่งซื้อ'],['received','วันที่รับเงิน'],['refunded','วันที่คืนเงิน']].map(([k,t])=>`<option value="${k}" ${basis===k?'selected':''}>${t}</option>`).join('')}</select></label><label>รายการที่แสดง<select name="filter"><option value="all" ${filter==='all'?'selected':''}>ทั้งหมด</option><option value="refund" ${filter==='refund'?'selected':''}>ยกเลิก / ส่งคืน ที่ต้องตรวจคืนเงิน</option></select></label></div></details></form><p class="muted">ข้อมูลช่วง ${from||"ตั้งแต่เริ่ม"} ถึง ${to||"ปัจจุบัน"} (เวลาไทย)</p><div class="metrics">${cards.map(([title,value,note])=>`<div class="metric"><span>${title}</span><strong>${money(value)} <small>บาท</small></strong><small>${note}</small></div>`).join('')}</div><p class="muted">ยอดสั่งซื้อนับตามวันสั่ง เงินรับนับตามวันรับเงิน และเงินคืนนับตามวันคืนเงิน (เวลาไทย) • รายงานนี้เป็นยอดหนังสือ • รายการยกเลิกยังแสดงในรายงานเพื่อตรวจสอบ แต่ไม่รวมยอดขาย</p>`}
 <section class="panel"><div class="actions"><h2>${section==='finance'?'💳 สลิปรอตรวจ':section==='finance-cod'?'🚚 เงินปลายทางรอรับ':'🧾 รายการออเดอร์'}</h2>${!queue?'<button id="finance-download" class="primary">📥 ดาวน์โหลด Excel</button>':''}<button id="finance-reload">↻ โหลดใหม่</button></div><p class="muted">${money(data.total)} รายการ • ${queue?'ค้างทั้งหมด':'รายการตาม'+({ordered:'วันที่สั่งซื้อ',received:'วันที่รับเงิน',refunded:'วันที่คืนเงิน'}[basis])}</p><div class="order-list">${data.orders.map(o=>`<article class="order-card"><div><b>BB${String(o.number).padStart(6,'0')}</b><p class="muted">สั่ง ${date(o.created_at)}</p></div><div><b>${o.package==='bundle'?'หนังสือ + เว็บ Prompt':'หนังสือ 1 เล่ม'}</b><p>${money(o.amount)} บาท · ${o.method==='cod'?'เก็บปลายทาง':'โอนเงิน'}</p></div><div><span class="badge">${esc(payment[o.payment_status])}</span><p>${esc(shipping[o.status])}</p>${o.paid_at?`<small>รับเงิน ${date(o.paid_at)}</small>`:''}${o.refunded_at?`<p class="small-text">คืนเงิน ${date(o.refunded_at)}</p>`:''}${o.tracking?`<p class="small-text">DHL ${esc(o.tracking)}</p>`:''}</div><div><button data-finance-detail="${o.id}" class="primary">${section==='finance'?'🔎 ตรวจสลิป':'เปิดรายละเอียด →'}</button></div></article>`).join('')||'<div class="empty">🌿 ไม่มีรายการในช่วงนี้</div>'}</div><div class="pager"><button id="finance-prev" ${page===0?'disabled':''}>← ก่อนหน้า</button><span>${page+1} / ${Math.max(1,Math.ceil(data.total/50))}</span><button id="finance-next" ${(page+1)*50>=data.total?'disabled':''}>ถัดไป →</button></div><p id="finance-message" role="status"></p></section>`;
 const run=(button,fn)=>async()=>{button.disabled=true;try{await fn();}catch(e){$('#finance-message').textContent=e.message;}finally{button.disabled=false;}};
 const again=()=>render(section,api,detail);
 for(const b of document.querySelectorAll('[data-finance-detail]'))b.onclick=run(b,()=>detail(b.dataset.financeDetail));
 $('#finance-reload').onclick=run($('#finance-reload'),again);
 $('#finance-prev').onclick=run($('#finance-prev'),async()=>{page--;await again();});$('#finance-next').onclick=run($('#finance-next'),async()=>{page++;await again();});
 if(!queue){const f=$('#finance-dates');f.elements.preset.onchange=()=>{const p=f.elements.preset.value,d=today();f.elements.from.value=p==='today'?d:p==='month'?d.slice(0,7)+'-01':'';f.elements.to.value=['today','month'].includes(p)?d:'';$('#finance-advanced').open=p==='custom';};for(const name of ['from','to'])f.elements[name].onchange=()=>f.elements.preset.value='custom';
 f.onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{const v=Object.fromEntries(new FormData(f));if(v.from&&v.to&&v.from>v.to)throw Error('วันเริ่มต้องไม่เกินวันสิ้นสุด');from=v.from;to=v.to;preset=v.preset;basis=v.basis;filter=v.filter;page=0;await again();})();};
 $('#finance-download').onclick=run($('#finance-download'),async()=>{const report=await api('finance_report',{...params,export:true});const sum=report.summary;const rows=[['เลขออเดอร์','วันที่สั่งซื้อ (ไทย)','สินค้า','ยอดออเดอร์ (บาท)','วิธีชำระ','สถานะเงิน','วันที่รับเงิน (ไทย)','ยอดรับเดิม (บาท)','วันที่คืนเงิน (ไทย)','ยอดคืน (บาท)','สถานะจัดส่ง','เลขพัสดุ','หมายเหตุการเงิน'],...report.orders.map(o=>['BB'+String(o.number).padStart(6,'0'),date(o.created_at),o.package==='bundle'?'หนังสือ + เว็บ Prompt':'หนังสือ 1 เล่ม',o.amount,o.method==='cod'?'เก็บเงินปลายทาง':'โอนเงิน',payment[o.payment_status],date(o.paid_at),o.paid_at?o.cash_amount:0,date(o.refunded_at),o.refunded_at?o.cash_amount:0,shipping[o.status],o.tracking||'',o.payment_note||'']),[],['สรุปยอดหนังสือ',from||'ตั้งแต่เริ่ม',to||'ถึงปัจจุบัน'],['ยอดสั่งซื้อตามวันสั่ง',sum.ordered],['เงินโอนตามวันรับ',sum.transfer_received],['เงิน DHL ตามวันรับ',sum.cod_received],['คืนเงินตามวันคืน',sum.refunded],['รับสุทธิในช่วงเวลา',sum.transfer_received+sum.cod_received-sum.refunded],['สลิปรอตรวจทั้งหมด',sum.review],['ปลายทางรอรับทั้งหมด',sum.pending_cod],['รายการด้านบนเลือกตาม',{ordered:'วันที่สั่งซื้อ',received:'วันที่รับเงิน',refunded:'วันที่คืนเงิน'}[basis]],['ตัวกรองรายการ',filter==='refund'?'ยกเลิก / ส่งคืน':'ทั้งหมด'],['หมายเหตุ','ยอดสรุปตามช่วงเวลา ไม่จำกัดด้วยตัวกรองรายการยกเลิก / ส่งคืน']];window.bookExport.download(window.bookExport.grid(rows,report.total+1),`บัญชีหนังสือ-${from||'ทั้งหมด'}-${to||today()}.xlsx`);$('#finance-message').textContent='ดาวน์โหลดแล้ว '+report.total+' รายการ';});}
}
window.bookFinance={render};
})();
