(() => {
 'use strict';
 const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],form=$('#checkout');
 const read=(k,session=false)=>{try{return (session?sessionStorage:localStorage).getItem(k)}catch{return null}};
 const save=(k,v,session=false)=>{try{(session?sessionStorage:localStorage).setItem(k,v)}catch{}};
 const uuid=()=>crypto.randomUUID(),key=read('bb_book_key',true)||uuid()+uuid();save('bb_book_key',key,true);
 let draft=null;try{const d=JSON.parse(read('bb_book_draft',true)||'null');if(d&&Date.now()-d.at<3600000)draft=d.data;}catch{}
 let addresses=[],pending=null;
 // This sales page no longer collects optional analytics or advertising events.
 try{localStorage.removeItem('bb_book_consent');for(const k of ['bb_book_sid','bb_book_utm'])sessionStorage.removeItem(k);}catch{}
 async function api(op,data){const r=await fetch(`/api/book?op=${op}`,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});let d;try{d=await r.json()}catch{throw Error('ระบบขัดข้องชั่วคราว กรุณาลองใหม่')}if(!r.ok)throw Error(d.error||'ทำรายการไม่สำเร็จ');return d;}
 const prices={book:345,bundle:490},names={book:'หนังสือ 1 เล่ม',bundle:'หนังสือ + เว็บรวม Prompt'};
 function selected(n){return form.querySelector(`input[name="${n}"]:checked`).value;}
 function update(){const p=selected('package'),m=selected('method');$$('.total').forEach(e=>e.textContent=prices[p]);$('#summary-package').textContent=names[p];$('#bank-panel').hidden=m!=='transfer';$('#submit-order').textContent=`ยืนยันสั่งซื้อ • ${m==='cod'?'เก็บเงินปลายทาง':'โอนเงิน'} ${prices[p]} บาท`;}
 $$('input[name="package"]').forEach(e=>e.addEventListener('change',()=>{update();}));
 $$('input[name="method"]').forEach(e=>e.addEventListener('change',()=>{update();}));
 function saveDraft(){const data=Object.fromEntries(new FormData(form));delete data.website;if(!addresses.length&&draft){for(const k of ['province','district','subdistrict','postcode'])data[k]=draft[k]||'';}save('bb_book_draft',JSON.stringify({at:Date.now(),data}),true);}
 $$('[data-package]').forEach(e=>e.addEventListener('click',()=>{form.querySelector(`input[value="${e.dataset.package}"]`).checked=true;update();saveDraft();}));
 for(const type of ['input','change'])form.addEventListener(type,saveDraft);
 if(draft){for(const k of ['first_name','last_name','phone','address','note'])form.elements[k].value=draft[k]||'';for(const k of ['package','method']){const el=[...form.querySelectorAll('input[name='+k+']')].find(x=>x.value===draft[k]);if(el)el.checked=true;}if(draft.method==='transfer')$('#slip-name').textContent='ข้อมูลเดิมยังอยู่ กรุณาแนบรูปสลิปอีกครั้งก่อนยืนยัน';}
 update();
 const checkoutVisibility=new IntersectionObserver(entries=>{const visible=entries[0].isIntersecting;document.body.classList.toggle('checkout-visible',visible);},{threshold:0});checkoutVisibility.observe($('#order'));
 function options(name,values,label,current=''){const e=form.elements[name];e.replaceChildren(new Option(label,''),...values.map(v=>new Option(v,v)));e.value=current;e.disabled=!values.length;}
 const unique=(rows,i)=>[...new Set(rows.map(a=>a[i]))].sort((a,b)=>a.localeCompare(b,'th'));
 function districts(){const rows=addresses.filter(a=>a[2]===form.elements.province.value);options('district',unique(rows,1),'เลือกอำเภอ / เขต');options('subdistrict',[],'เลือกตำบล / แขวง');options('postcode',[],'เลือกรหัสไปรษณีย์');}
 function subdistricts(){options('subdistrict',unique(addresses.filter(a=>a[2]===form.elements.province.value&&a[1]===form.elements.district.value),0),'เลือกตำบล / แขวง');options('postcode',[],'เลือกรหัสไปรษณีย์');}
 function postcodes(){const rows=addresses.filter(a=>a[2]===form.elements.province.value&&a[1]===form.elements.district.value&&a[0]===form.elements.subdistrict.value),values=unique(rows,3);options('postcode',values,'เลือกรหัสไปรษณีย์',values.length===1?values[0]:'');}
 form.elements.province.addEventListener('change',districts);form.elements.district.addEventListener('change',subdistricts);form.elements.subdistrict.addEventListener('change',postcodes);
 function choose(a){form.elements.province.value=a[2];districts();form.elements.district.value=a[1];subdistricts();form.elements.subdistrict.value=a[0];postcodes();form.elements.postcode.value=a[3];$('#address-search').value=`${a[0]} / ${a[1]} / ${a[2]} / ${a[3]}`;$('#address-results').hidden=true;$('#address-search').setAttribute('aria-expanded','false');$('#address-help').textContent='เติมที่อยู่แล้ว ตรวจสอบจังหวัด อำเภอ ตำบล และรหัสไปรษณีย์ด้านล่างได้';saveDraft();form.elements.province.focus();}
 $('#address-search').addEventListener('input',()=>{const query=$('#address-search').value.trim(),list=$('#address-results');list.replaceChildren();const matches=query.length>=2?addresses.filter(a=>a.join(' ').includes(query)).slice(0,40):[];for(const a of matches){const b=document.createElement('button');b.type='button';b.setAttribute('role','option');b.textContent=`${a[0]} / ${a[1]} / ${a[2]} / ${a[3]}`;b.addEventListener('click',()=>choose(a));list.append(b);}list.hidden=!matches.length;$('#address-search').setAttribute('aria-expanded',String(!!matches.length));$('#address-help').textContent=query.length>=2&&!matches.length?'ไม่พบรายการ ลองพิมพ์บางส่วนของตำบล หรือเลือกจังหวัดด้านล่าง':'เลือกครั้งเดียว ระบบเติมอำเภอ จังหวัด และรหัสไปรษณีย์ให้';});
 function closeAddressList(){$('#address-results').hidden=true;$('#address-search').setAttribute('aria-expanded','false');}
 $('#address-search').addEventListener('keydown',e=>{if(e.key==='ArrowDown'&&!$('#address-results').hidden&&$('#address-results button')){e.preventDefault();$('#address-results button').focus()}if(e.key==='Escape')closeAddressList();if(e.key==='Enter'&&!$('#address-results').hidden&&$('#address-results button')){e.preventDefault();$('#address-results button').click()}});
 $('#address-results').addEventListener('keydown',e=>{if(e.key==='Escape'){closeAddressList();$('#address-search').focus()}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();(e.key==='ArrowDown'?e.target.nextElementSibling:e.target.previousElementSibling)?.focus()}});
 document.addEventListener('focusin',e=>{if(e.target!==$('#address-search')&&!$('#address-results').contains(e.target))closeAddressList()});
 fetch('/book-assets/addresses.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(a=>{addresses=a;options('province',unique(a,2),'เลือกจังหวัด');if(draft){const row=addresses.find(x=>x[0]===draft.subdistrict&&x[1]===draft.district&&x[2]===draft.province&&x[3]===draft.postcode);if(row){form.elements.province.value=row[2];districts();form.elements.district.value=row[1];subdistricts();form.elements.subdistrict.value=row[0];postcodes();form.elements.postcode.value=row[3];}update();}}).catch(()=>{$('#address-help').textContent='โหลดรายชื่อจังหวัดไม่สำเร็จ กรุณาเชื่อมต่ออินเทอร์เน็ตแล้วโหลดหน้านี้ใหม่';});
 $('#copy-account').addEventListener('click',async()=>{try{await navigator.clipboard.writeText('1381082187');$('#copy-result').textContent='คัดลอกเลขบัญชีแล้ว';}catch{$('#copy-result').textContent='คัดลอกไม่สำเร็จ กดค้างที่เลขบัญชีเพื่อคัดลอกได้';}});
 let slipPreviewURL=null;
 function slipError(message){$('#slip-error').textContent=message;$('#slip-error').hidden=!message;$('#slip').setAttribute('aria-invalid',String(!!message));}
 $('#slip').addEventListener('change',()=>{if(slipPreviewURL)URL.revokeObjectURL(slipPreviewURL);slipPreviewURL=null;$('#slip-preview').hidden=true;$('#slip-preview').removeAttribute('src');slipError('');const file=$('#slip').files[0];$('#slip-name').textContent='';if(!file)return;try{fileCheck(file);slipPreviewURL=URL.createObjectURL(file);$('#slip-preview').src=slipPreviewURL;$('#slip-preview').hidden=false;$('#slip-name').textContent=`เลือกสลิปแล้ว: ${file.name}`;}catch(err){slipError(err.message)}});
 function fileCheck(file){if(!file)throw Error('กรุณาแนบรูปสลิปก่อนยืนยัน');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('รับเฉพาะรูป JPG, PNG หรือ WebP');if(file.size>5242880)throw Error('รูปสลิปต้องไม่เกิน 5 MB');}
 async function upload(file,order){fileCheck(file);const image=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(Error('อ่านรูปไม่สำเร็จ'));r.readAsDataURL(file)});const result=await api('slip',{id:order.id,key,image});return result;}
 const statusText={new:'ทีมงานกำลังตรวจสอบคำสั่งซื้อ',ready:'เตรียมแพ็กและจัดส่ง',shipped:'จัดส่งแล้ว',delivered:'จัดส่งสำเร็จ',cancelled:'ยกเลิกคำสั่งซื้อ',returned:'พัสดุส่งคืน'};
 function success(o){save('bb_book_draft','null',true);pending=o;save('bb_book_order',JSON.stringify(o),true);form.hidden=true;$('#success').hidden=false;$('#order-number').textContent=o.number;$('#order-success-details').textContent=`${names[o.package]} • ${o.amount} บาท • ส่งฟรี`;$('#order-success-status').textContent=o.payment_status==='awaiting_slip'?('รอแนบสลิปการโอน'+(o.payment_note?' • '+o.payment_note:'')):o.payment_status==='review'?'ได้รับสลิปแล้ว รอทีมงานตรวจสอบยอดเงิน':`${statusText[o.status]||''}${o.tracking?` • DHL เลขพัสดุ ${o.tracking}`:''}`;$('#retry-slip').hidden=!(o.method==='transfer'&&o.payment_status==='awaiting_slip');$('.mobile-cta').hidden=true;}
 form.addEventListener('submit',async e=>{e.preventDefault();$('#form-error').hidden=true;const invalid=[...form.elements].find(el=>el.willValidate&&!el.checkValidity());if(invalid){invalid.reportValidity();invalid.focus();return;}const data=Object.fromEntries(new FormData(form));data.phone=data.phone.replace(/[\s-]/g,'');if(!/^0[0-9]{8,9}$/.test(data.phone)){form.elements.phone.focus();$('#form-error').textContent='กรุณาตรวจเบอร์โทรศัพท์ 9 ถึง 10 หลัก ขึ้นต้นด้วย 0';$('#form-error').hidden=false;return;}
  if(data.method==='transfer'){try{fileCheck($('#slip').files[0]);slipError('')}catch(err){slipError(err.message);$('#slip').focus();return;}}
  const button=$('#submit-order');button.disabled=true;button.textContent='กำลังบันทึกคำสั่งซื้อ...';
  try{if(data.method==='transfer')fileCheck($('#slip').files[0]);let o=await api('order',{...data,key,utm:{},session_id:null,analytics_consent:false,marketing_consent:false});success(o);if(o.method==='transfer'&&o.payment_status==='awaiting_slip'){try{o=await upload($('#slip').files[0],o);success(o)}catch(err){$('#success-message').textContent=err.message;}}$('#success').focus();$('#success').scrollIntoView({behavior:'smooth',block:'center'});}catch(err){$('#form-error').textContent=err.message;$('#form-error').hidden=false;$('#form-error').focus();}finally{button.disabled=false;update();}
 });
 $('#retry-upload').addEventListener('click',async()=>{const b=$('#retry-upload');b.disabled=true;try{success(await upload($('#retry-file').files[0],pending));$('#success-message').textContent='ส่งสลิปเรียบร้อย รอตรวจสอบ'}catch(e){$('#success-message').textContent=e.message}finally{b.disabled=false;}});
 $('#refresh-order').addEventListener('click',async()=>{try{success(await api('status',{id:pending.id,key}));$('#success-message').textContent='อัปเดตสถานะแล้ว'}catch(e){$('#success-message').textContent=e.message}});
 try{const old=JSON.parse(read('bb_book_order',true)||'null');if(old?.id){success(old);api('status',{id:old.id,key}).then(success).catch(()=>{})}}catch{}
})();
