(() => {
 'use strict';
 const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],form=$('#checkout');
 const read=(k,session=false)=>{try{return (session?sessionStorage:localStorage).getItem(k)}catch{return null}};
 const save=(k,v,session=false)=>{try{(session?sessionStorage:localStorage).setItem(k,v)}catch{}};
 const uuid=()=>crypto.randomUUID(),key=read('bb_book_key',true)||uuid()+uuid();save('bb_book_key',key,true);
 let consent=read('bb_book_consent'),config={},tracking=false,started=false,addresses=[],pending=null;
 const sid=read('bb_book_sid',true)||uuid();save('bb_book_sid',sid,true);
 const utm={};for(const k of ['utm_source','utm_medium','utm_campaign','utm_content','utm_term']){const v=new URL(location.href).searchParams.get(k);if(v&&/^[a-zA-Z0-9_-]{1,80}$/.test(v))utm[k]=v;}
 try{if(Object.keys(utm).length)save('bb_book_utm',JSON.stringify(utm),true);else Object.assign(utm,JSON.parse(read('bb_book_utm',true)||'{}'))}catch{}
 async function api(op,data){const r=await fetch(`/api/book?op=${op}`,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});let d;try{d=await r.json()}catch{throw Error('ระบบขัดข้องชั่วคราว กรุณาลองใหม่')}if(!r.ok)throw Error(d.error||'ทำรายการไม่สำเร็จ');return d;}
 const analytics=()=>consent==='analytics'||consent==='all';
 function event(name,data={}){if(!analytics())return;const payload={id:uuid(),session_id:sid,event:name,data,utm,consent:true};fetch('/api/book?op=event',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),keepalive:true}).catch(()=>{});if(window.gtag)window.gtag('event',name,{...data,...utm,page_location:'https://businessboy.ai/ai-book',page_title:'หนังสือ AI'});}
 function script(src){const s=document.createElement('script');s.src=src;s.async=true;document.head.append(s);}
 function startTracking(){if(!analytics()||tracking)return;tracking=true;
  const safeURL=new URL(location.origin+location.pathname);for(const [k,v] of Object.entries(utm))safeURL.searchParams.set(k,v);if(/^#[a-z_-]+$/.test(location.hash))safeURL.hash=location.hash;history.replaceState(null,'',safeURL.href);
  const live=['businessboy.ai','www.businessboy.ai'].includes(location.hostname);
  if(live&&config.ga4_id){window.dataLayer=window.dataLayer||[];window.gtag=function(){window.dataLayer.push(arguments)};window.gtag('consent','default',{analytics_storage:'granted',ad_storage:consent==='all'?'granted':'denied',ad_user_data:'denied',ad_personalization:consent==='all'?'granted':'denied'});window.gtag('js',new Date());window.gtag('config',config.ga4_id,{send_page_view:false,allow_google_signals:false,allow_ad_personalization_signals:false,page_location:'https://businessboy.ai/ai-book'});script(`https://www.googletagmanager.com/gtag/js?id=${encodeURIComponent(config.ga4_id)}`);}
  if(live&&consent==='all'&&config.pixel_id){const f=window.fbq=function(){f.callMethod?f.callMethod.apply(f,arguments):f.queue.push(arguments)};f.queue=[];f.loaded=true;f.version='2.0';window._fbq=f;f('set','autoConfig',false,config.pixel_id);f('init',config.pixel_id);f('consent','grant');script('https://connect.facebook.net/en_US/fbevents.js');f('track','PageView');f('track','ViewContent',{content_ids:['ai-book'],content_type:'product',currency:'THB'});}
  if(live&&config.clarity_id){window.clarity=function(){(window.clarity.q=window.clarity.q||[]).push(arguments)};window.clarity('consentv2',{ad_Storage:consent==='all'?'granted':'denied',analytics_Storage:'granted'});script(`https://www.clarity.ms/tag/${encodeURIComponent(config.clarity_id)}`);}
  event('page_view');
 }
 fetch('/api/book?op=config').then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{config=d;startTracking()}).catch(()=>{});
 $('#consent').hidden=!!consent;
 $$('[data-consent]').forEach(b=>b.addEventListener('click',()=>{const previous=consent;consent=b.dataset.consent;save('bb_book_consent',consent);$('#consent').hidden=true;if(tracking&&previous!==consent){if(window.fbq)window.fbq('consent','revoke');if(window.clarity)window.clarity('consentv2',{ad_Storage:'denied',analytics_Storage:'denied'});for(const c of document.cookie.split(';')){const name=c.split('=')[0].trim();if(/^(_ga|_gid|_gat|_fbp|_fbc|_clck|_clsk)/.test(name)){for(const domain of ['',`; domain=${location.hostname}`,'; domain=.businessboy.ai'])document.cookie=`${name}=; Max-Age=0; path=/${domain}`;}}location.reload();}else startTracking();}));
 $('#cookie-settings').addEventListener('click',()=>{$('#consent').hidden=false;$('#consent button').focus()});
 const prices={book:345,bundle:490},names={book:'หนังสือ 1 เล่ม',bundle:'หนังสือ + เว็บรวม Prompt'};
 function selected(n){return form.querySelector(`input[name="${n}"]:checked`).value;}
 function update(){const p=selected('package'),m=selected('method');$$('.total').forEach(e=>e.textContent=prices[p]);$('#summary-package').textContent=names[p];$('#bank-panel').hidden=m!=='transfer';$('#submit-order').textContent=`ยืนยันสั่งซื้อ • ${m==='cod'?'เก็บเงินปลายทาง':'โอนเงิน'} ${prices[p]} บาท`;}
 $$('input[name="package"]').forEach(e=>e.addEventListener('change',()=>{update();event('select_package',{package:selected('package')})}));
 $$('input[name="method"]').forEach(e=>e.addEventListener('change',()=>{update();event('payment_select',{method:selected('method')})}));
 $$('[data-package]').forEach(e=>e.addEventListener('click',()=>{form.querySelector(`input[value="${e.dataset.package}"]`).checked=true;update();event('select_package',{package:e.dataset.package})}));
 form.addEventListener('focusin',()=>{if(!started){started=true;event('checkout_start');if(window.fbq)window.fbq('track','InitiateCheckout',{currency:'THB',value:prices[selected('package')]});}});
 let active=0,last=performance.now(),idle=Date.now(),engagementSent=false;
 for(const e of ['pointerdown','keydown','scroll'])window.addEventListener(e,()=>{idle=Date.now()},{passive:true});
 setInterval(()=>{const now=performance.now();if(!document.hidden&&Date.now()-idle<60000)active+=(now-last)/1000;last=now;},1000);
 function engagement(){if(active>0&&!engagementSent){engagementSent=true;event('engagement',{seconds:Math.round(active)});}}
 window.addEventListener('pagehide',engagement);document.addEventListener('visibilitychange',()=>{if(document.hidden)engagement();else{active=0;engagementSent=false;last=performance.now();}});
 const sections=new Set();new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting&&analytics()&&!sections.has(e.target.id)){sections.add(e.target.id);event('section_view',{section:e.target.id})}}),{threshold:.15}).observe($('#order'));
 const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting&&analytics()&&!sections.has(e.target.id)){sections.add(e.target.id);event('section_view',{section:e.target.id})}}),{threshold:.2});$$('section[id]').forEach(e=>observer.observe(e));
 const scrolls=new Set();window.addEventListener('scroll',()=>{const pct=Math.round((scrollY+innerHeight)/document.documentElement.scrollHeight*100);for(const n of [25,50,75,100])if(pct>=n&&!scrolls.has(n)&&analytics()){scrolls.add(n);event('scroll',{percent:n});}},{passive:true});
 function options(name,values,label,current=''){const e=form.elements[name];e.replaceChildren(new Option(label,''),...values.map(v=>new Option(v,v)));e.value=current;e.disabled=!values.length;}
 const unique=(rows,i)=>[...new Set(rows.map(a=>a[i]))].sort((a,b)=>a.localeCompare(b,'th'));
 function districts(){const rows=addresses.filter(a=>a[2]===form.elements.province.value);options('district',unique(rows,1),'เลือกอำเภอ / เขต');options('subdistrict',[],'เลือกตำบล / แขวง');options('postcode',[],'เลือกรหัสไปรษณีย์');}
 function subdistricts(){options('subdistrict',unique(addresses.filter(a=>a[2]===form.elements.province.value&&a[1]===form.elements.district.value),0),'เลือกตำบล / แขวง');options('postcode',[],'เลือกรหัสไปรษณีย์');}
 function postcodes(){const rows=addresses.filter(a=>a[2]===form.elements.province.value&&a[1]===form.elements.district.value&&a[0]===form.elements.subdistrict.value),values=unique(rows,3);options('postcode',values,'เลือกรหัสไปรษณีย์',values.length===1?values[0]:'');}
 form.elements.province.addEventListener('change',districts);form.elements.district.addEventListener('change',subdistricts);form.elements.subdistrict.addEventListener('change',postcodes);
 function choose(a){form.elements.province.value=a[2];districts();form.elements.district.value=a[1];subdistricts();form.elements.subdistrict.value=a[0];postcodes();form.elements.postcode.value=a[3];$('#address-search').value=`${a[0]} / ${a[1]} / ${a[2]} / ${a[3]}`;$('#address-results').hidden=true;$('#address-search').setAttribute('aria-expanded','false');form.elements.note.focus();}
 $('#address-search').addEventListener('input',()=>{const query=$('#address-search').value.trim(),list=$('#address-results');list.replaceChildren();const matches=query.length>=2?addresses.filter(a=>a.join(' ').includes(query)).slice(0,40):[];for(const a of matches){const b=document.createElement('button');b.type='button';b.setAttribute('role','option');b.textContent=`${a[0]} / ${a[1]} / ${a[2]} / ${a[3]}`;b.addEventListener('click',()=>choose(a));list.append(b);}list.hidden=!matches.length;$('#address-search').setAttribute('aria-expanded',String(!!matches.length));$('#address-help').textContent=query.length>=2&&!matches.length?'ไม่พบรายการ ลองพิมพ์บางส่วนของตำบล หรือเลือกจังหวัดด้านล่าง':'เลือกครั้งเดียว ระบบเติมอำเภอ จังหวัด และรหัสไปรษณีย์ให้';});
 $('#address-search').addEventListener('keydown',e=>{if(e.key==='ArrowDown'&&$('#address-results button')){e.preventDefault();$('#address-results button').focus()}});
 $('#address-results').addEventListener('keydown',e=>{if(e.key==='Escape'){$('#address-results').hidden=true;$('#address-search').focus()}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();(e.key==='ArrowDown'?e.target.nextElementSibling:e.target.previousElementSibling)?.focus()}});
 fetch('/book-assets/addresses.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(a=>{addresses=a;options('province',unique(a,2),'เลือกจังหวัด')}).catch(()=>{$('#address-help').textContent='โหลดรายชื่อจังหวัดไม่สำเร็จ กรุณาเชื่อมต่ออินเทอร์เน็ตแล้วโหลดหน้านี้ใหม่';});
 $('#copy-account').addEventListener('click',async()=>{try{await navigator.clipboard.writeText('1381082187');$('#copy-result').textContent='คัดลอกเลขบัญชีแล้ว';event('copy_account')}catch{$('#copy-result').textContent='คัดลอกไม่สำเร็จ กดค้างที่เลขบัญชีเพื่อคัดลอกได้';}});
 $('#save-qr').addEventListener('click',()=>event('save_qr'));
 $('#slip').addEventListener('change',()=>{$('#slip-name').textContent=$('#slip').files[0]?`เลือกรูปแล้ว: ${$('#slip').files[0].name}`:''});
 function fileCheck(file){if(!file)throw Error('กรุณาแนบรูปสลิปก่อนยืนยัน');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('รับเฉพาะรูป JPG, PNG หรือ WebP');if(file.size>5242880)throw Error('รูปสลิปต้องไม่เกิน 5 MB');}
 async function upload(file,order){fileCheck(file);const image=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(Error('อ่านรูปไม่สำเร็จ'));r.readAsDataURL(file)});const result=await api('slip',{id:order.id,key,image});event('slip_uploaded');return result;}
 const statusText={new:'ทีมงานกำลังตรวจสอบคำสั่งซื้อ',ready:'เตรียมแพ็กและจัดส่ง',shipped:'จัดส่งแล้ว',delivered:'จัดส่งสำเร็จ',cancelled:'ยกเลิกคำสั่งซื้อ',returned:'พัสดุส่งคืน'};
 function success(o){pending=o;save('bb_book_order',JSON.stringify(o),true);form.hidden=true;$('#success').hidden=false;$('#order-number').textContent=o.number;$('#order-success-details').textContent=`${names[o.package]} • ${o.amount} บาท • ส่งฟรี`;$('#order-success-status').textContent=o.payment_status==='awaiting_slip'?'รอแนบสลิปการโอน':o.payment_status==='review'?'ได้รับสลิปแล้ว รอทีมงานตรวจสอบยอดเงิน':`${statusText[o.status]||''}${o.tracking?` • DHL เลขพัสดุ ${o.tracking}`:''}`;$('#retry-slip').hidden=!(o.method==='transfer'&&o.payment_status==='awaiting_slip');$('.mobile-cta').hidden=true;}
 form.addEventListener('submit',async e=>{e.preventDefault();$('#form-error').hidden=true;const invalid=[...form.elements].find(el=>el.willValidate&&!el.checkValidity());if(invalid){invalid.reportValidity();invalid.focus();event('form_error',{field:invalid.name});return;}const data=Object.fromEntries(new FormData(form));data.phone=data.phone.replace(/[\s-]/g,'');if(!/^0[0-9]{8,9}$/.test(data.phone)){form.elements.phone.focus();$('#form-error').textContent='กรุณาตรวจเบอร์โทรศัพท์ 9 ถึง 10 หลัก ขึ้นต้นด้วย 0';$('#form-error').hidden=false;return;}
  const button=$('#submit-order');button.disabled=true;button.textContent='กำลังบันทึกคำสั่งซื้อ...';
  try{if(data.method==='transfer')fileCheck($('#slip').files[0]);let o=await api('order',{...data,key,utm,session_id:analytics()?sid:null,analytics_consent:analytics(),marketing_consent:consent==='all'});success(o);event('order_submitted',{package:o.package,method:o.method});if(window.fbq)window.fbq('trackCustom','OrderSubmitted',{currency:'THB',value:o.amount,content_ids:[o.package]},{eventID:o.id});if(o.method==='transfer'&&o.payment_status==='awaiting_slip'){try{o=await upload($('#slip').files[0],o);success(o)}catch(err){$('#success-message').textContent=err.message;}}$('#success').focus();$('#success').scrollIntoView({behavior:'smooth',block:'center'});}catch(err){$('#form-error').textContent=err.message;$('#form-error').hidden=false;$('#form-error').focus();event('form_error',{field:'submit'});}finally{button.disabled=false;update();}
 });
 $('#retry-upload').addEventListener('click',async()=>{const b=$('#retry-upload');b.disabled=true;try{success(await upload($('#retry-file').files[0],pending));$('#success-message').textContent='ส่งสลิปเรียบร้อย รอตรวจสอบ'}catch(e){$('#success-message').textContent=e.message}finally{b.disabled=false;}});
 $('#refresh-order').addEventListener('click',async()=>{try{success(await api('status',{id:pending.id,key}));$('#success-message').textContent='อัปเดตสถานะแล้ว'}catch(e){$('#success-message').textContent=e.message}});
 try{const old=JSON.parse(read('bb_book_order',true)||'null');if(old?.id){success(old);api('status',{id:old.id,key}).then(success).catch(()=>{})}}catch{}
})();
