import { build } from 'esbuild';
import { writeFile } from 'node:fs/promises';

const result = await build({
  entryPoints: ['gen3-src/app.tsx'],
  bundle: true,
  minify: true,
  write: false,
  platform: 'browser',
  target: ['es2020'],
  define: { 'process.env.NODE_ENV': '"production"' },
  legalComments: 'none',
});

if (result.outputFiles.length !== 1) {
  throw new Error(`Expected one Gen 3 browser bundle, received ${result.outputFiles.length}`);
}
const [browserBundle] = result.outputFiles;

const privateBundleModule = [
  "'use strict';",
  '',
  '// Generated by build-gen3.mjs. Do not edit this file directly.',
  `module.exports = Object.freeze({ identity: ${JSON.stringify(browserBundle.text)} });`,
  '',
].join('\n');

await writeFile(new URL('./api/_gen3-bundle.js', import.meta.url), privateBundleModule, 'utf8');
