import { build } from 'esbuild';
import { writeFile } from 'node:fs/promises';

async function buildBrowserBundle(entryPoint) {
  const result = await build({
    entryPoints: [entryPoint],
    bundle: true,
    minify: true,
    write: false,
    platform: 'browser',
    target: ['es2020'],
    define: { 'process.env.NODE_ENV': '"production"' },
    legalComments: 'none',
  });

  if (result.outputFiles.length !== 1) {
    throw new Error(`Expected one browser bundle for ${entryPoint}, received ${result.outputFiles.length}`);
  }
  return result.outputFiles[0].text;
}

const [identityBundle, salesBundle, productsBundle, presenterIdentityBundle, presenterSalesBundle] = await Promise.all([
  buildBrowserBundle('gen3-src/app.tsx'),
  buildBrowserBundle('gen3-src/sales-app.tsx'),
  buildBrowserBundle('gen3-src/products-app.tsx'),
  buildBrowserBundle('gen3-src/presenter-identity-app.tsx'),
  buildBrowserBundle('gen3-src/presenter-sales-app.tsx'),
]);

const privateBundleModule = [
  "'use strict';",
  '',
  '// Generated by build-gen3.mjs. Do not edit this file directly.',
  `module.exports = Object.freeze({ identity: ${JSON.stringify(identityBundle)}, sales: ${JSON.stringify(salesBundle)}, products: ${JSON.stringify(productsBundle)}, presenterIdentity: ${JSON.stringify(presenterIdentityBundle)}, presenterSales: ${JSON.stringify(presenterSalesBundle)} });`,
  '',
].join('\n');

await writeFile(new URL('./api/_gen3-bundle.js', import.meta.url), privateBundleModule, 'utf8');
