// Run after changing Gen4 source. Protected source files are excluded from static deployment.
const fs = require('node:fs');
const path = require('node:path');
const read = file => fs.readFileSync(path.join(__dirname, file), 'utf8');
function page(file) {
  return read(file).replace('</head>', '<link rel="stylesheet" href="/gen4-assets/access-v01.css"><script defer src="/gen4-assets/access-v01.js"></script></head>')
    .replace(/<span class="cohort">([\s\S]*?)<\/span><\/span>/, '<div class="access-actions"><span class="cohort">$1</span></span><button class="access-logout" id="gen4-logout" type="button">ออกจากระบบ</button></div>');
}
const scripts = Object.fromEntries(['prompt-tool-v04.mjs', 'templates-v01.mjs', 'template-library-v01.mjs', 'template-catalog-v01.mjs', 'templates-customer-v01.mjs'].map(file => [file, read(`gen4-assets/${file}`)]));
const bundle = { pages: { hub: page('gen4.html'), prompt: page('gen4-meta-ai-prompt.html') }, login: read('gen4-login.html'), scripts };
fs.writeFileSync(path.join(__dirname, 'api/_gen4-content.js'), '// Generated by build-gen4.cjs. Do not edit directly.\nmodule.exports = ' + JSON.stringify(bundle) + ';\n');
console.log('Gen4 private content bundle generated');
