'use strict';
const $=s=>document.querySelector(s),categories=['เพจเล่าข่าว','เพจเล่าเรื่อง','คลิปขายแนวโกดัง','สร้างตัวตน + ขายของ','คาแรกเตอร์หนุ่มหล่อสาวสวย','เพจสายมู'];
let offset=0,loading=false;
function message(text){$('#admin-message').textContent=text;$('#admin-message').hidden=!text;}
async function api(url,options){const response=await fetch(url,{cache:'no-store',...options}),result=await response.json();if(!response.ok){if(response.status===401){$('#admin-login').hidden=false;$('#admin-content').hidden=true;$('#submissions').replaceChildren();}throw new Error(result.error||'โหลดไม่สำเร็จ');}return result;}
function line(dl,label,value){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=String(value??'');dl.append(dt,dd);}
async function list(){if(loading)return;loading=true;message('กำลังโหลดข้อมูล…');try{const generation=$('#generation-filter').value,result=await api('/api/homework?action=list&generation='+generation+'&offset='+offset);$('#submissions').replaceChildren();$('#total').textContent='ส่งการบ้านแล้ว '+result.total.toLocaleString('th-TH')+' รายการ';for(const row of result.rows){const card=document.createElement('article'),title=document.createElement('h2'),dl=document.createElement('dl');card.className='submission';title.textContent=row.full_name;card.append(title,dl);line(dl,'ส่งเมื่อ',new Date(row.created_at).toLocaleString('th-TH',{timeZone:'Asia/Bangkok'}));line(dl,'เลขยืนยัน','G4-EP1-'+row.id.toUpperCase());line(dl,'เบอร์โทรศัพท์',row.phone);line(dl,'ชื่อ Facebook',row.facebook_name);line(dl,'รุ่นผู้เรียน',row.generation);line(dl,'แนวเพจ',categories[row.category-1]);line(dl,'ชื่อเพจ',row.page_name);line(dl,'เหตุผลที่เลือกแนวเพจ',row.reason);line(dl,'เจอครั้งแรกจากที่ไหน',row.discovered);line(dl,'เหตุผลที่เลือกเรียน',row.decision);if(row.full_name==='ทดสอบระบบ Gen4 EP1 — ไม่ใช่นักเรียน'&&row.phone==='0000000000'&&row.page_name==='QA EP1 ทดสอบระบบเท่านั้น'){const hide=document.createElement('button');hide.type='button';hide.textContent='ซ่อนรายการทดสอบระบบ';hide.addEventListener('click',async()=>{hide.disabled=true;try{await api('/api/homework?action=archive-test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:row.id})});await list();}catch(e){message(e.message);hide.disabled=false;}});card.append(hide);}$('#submissions').append(card);}$('#previous').disabled=offset===0;$('#next').disabled=offset+50>=result.total;$('#page-number').textContent='หน้า '+(Math.floor(offset/50)+1);message(result.total?'':'ยังไม่มีการบ้านที่ส่งเข้ามาครับ');}catch(e){message(e.message);}finally{loading=false;}}
async function session(){try{const s=await api('/api/homework?action=session');$('#admin-login').hidden=s.authenticated;$('#admin-content').hidden=!s.authenticated;if(s.authenticated)await list();}catch(e){message(e.message);}}
$('#admin-login').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{await api('/api/student-story?action=login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('#password').value})});$('#password').value='';await session();}catch(e){message(e.message);}finally{button.disabled=false;}});
$('#generation-filter').addEventListener('change',()=>{offset=0;list();});$('#refresh').addEventListener('click',list);$('#previous').addEventListener('click',()=>{if(!loading){offset=Math.max(0,offset-50);list();}});$('#next').addEventListener('click',()=>{if(!loading){offset+=50;list();}});
$('#logout').addEventListener('click',async()=>{try{await api('/api/student-story?action=logout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});$('#submissions').replaceChildren();await session();}catch(e){message(e.message);}});
$('#export').addEventListener('click',async()=>{const button=$('#export');button.disabled=true;message('กำลังเตรียมไฟล์…');try{const response=await fetch('/api/homework?action=export&generation='+$('#generation-filter').value,{cache:'no-store'});if(!response.ok){const result=await response.json();throw new Error(result.error||'ส่งออกไม่สำเร็จ');}const blob=await response.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='gen4-ep1-homework.csv';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);message('ดาวน์โหลดไฟล์แล้ว เปิดด้วย Excel หรือ Google Sheets ได้ครับ');}catch(e){message(e.message);}finally{button.disabled=false;}});
session();
