const test=require('node:test'),assert=require('node:assert/strict');
const handler=require('../api/homework-ep3');const {validate,reviewInput,isOpen,pageKey,DEADLINE}=handler._test;
const valid={requestId:'cd0c936b-78da-4bde-bf55-d9aaea82556a',fullName:'ผู้เรียนทดสอบ',phone:'0812345678',facebookName:'Test Student',generation:4,pageName:'ชื่อเพจทดสอบ',pageUrl:'facebook.com/testpage',pageCreatedDate:'2026-10-11'};
test('EP3 accepts a page with no clips and ignores self-awarded review flags',()=>{const v=validate({...valid,review_status:'complete',dailyVerified:true});assert.equal(v.pageName,valid.pageName);assert.equal(v.review_status,undefined);assert.equal(v.dailyVerified,undefined);});
test('dates strictly after October 10 and within the deadline window',()=>{for(const date of ['2026-10-10','2026-10-24','2026-10-99','11/10/2026',''])assert.throws(()=>validate({...valid,pageCreatedDate:date}));assert.equal(validate({...valid,pageCreatedDate:'2026-10-23'}).pageCreatedDate,'2026-10-23');});
test('duplicate keys normalize Facebook aliases, tabs, trailing slash, case and profile IDs',()=>{const key=u=>pageKey(validate({...valid,pageUrl:u}).pageUrl);for(const url of ['https://www.facebook.com/TestPage/','https://m.facebook.com/testpage?fbclid=123','https://fb.com/TESTPAGE','https://facebook.com/testpage/about'])assert.equal(key(url),key(valid.pageUrl));assert.equal(key('https://facebook.com/profile.php?id=123'),key('https://facebook.com/pages/Test/123/'));assert.equal(key('https://facebook.com/123'),key('https://facebook.com/profile.php?id=123'));});
test('review needs daily evidence, three checks and a dated note before pass',()=>{const v={id:valid.requestId,version:0,status:'complete',dailyClips:[{date:'2026-10-11',count:5}],dateVerified:true,scenesVerified:true,dailyVerified:true,note:'ตรวจช่วงวันที่ 11 ตุลาคม'};assert.equal(reviewInput(v).status,'complete');for(const change of [{dailyClips:[]},{dailyClips:[{date:'2026-10-11',count:4}]},{dailyClips:[{date:'2026-10-11',count:5},{date:'2026-10-11',count:5}]},{dateVerified:false},{scenesVerified:false},{dailyVerified:false},{note:''},{version:-1}])assert.throws(()=>reviewInput({...v,...change}));assert.equal(reviewInput({...v,status:'progress',dailyClips:[],note:''}).status,'progress');});
function request(method,action,body,headers={}){return new Promise(async resolve=>{await handler({method,query:{action},body,headers:{host:'localhost:4393',...headers}},{setHeader(){},end(value){resolve({status:this.statusCode,data:JSON.parse(value)});}});});}
test('private endpoints require authentication and cross-site submissions fail',async()=>{for(const action of ['list','export'])assert.equal((await request('GET',action)).status,401);const h={origin:'http://localhost:4393','content-type':'application/json'};for(const action of ['review','archive-test'])assert.equal((await request('POST',action,{},h)).status,401);assert.equal((await request('POST','submit',valid,{...h,origin:'https://evil.test'})).status,403);assert.equal((await request('POST','submit',{...valid,pageUrl:'https://facebook.com/reel/123'},h)).data.field,'pageUrl');});
test('EP3 deadline closes at exactly Bangkok noon and config discloses no learner information',async()=>{const r=await request('GET','config');assert.equal(r.data.assignment,'gen4-ep3');assert.deepEqual(Object.keys(r.data).sort(),['assignment','deadline','open','serverTime']);assert.equal(DEADLINE,'2026-10-23T05:00:00.000Z');assert.equal(isOpen(Date.parse(DEADLINE)-1),true);assert.equal(isOpen(Date.parse(DEADLINE)),false);});
