const test=require('node:test'),assert=require('node:assert/strict');
const handler=require('../api/homework');const {validate,isOpen,csvCell,payloadHash,authenticated,DEADLINE}=handler._test;
const valid={requestId:'cd0c936b-78da-4bde-bf55-d9aaea82556a',fullName:'ผู้เรียนทดสอบ',phone:'0812345678',facebookName:'Test Student',generation:4,category:6,pageName:'ชื่อเพจทดสอบ',reason:'อยากลองเล่าเรื่อง',discovered:'จากคลิปในเพจ',decision:'อยากเรียนรู้วิธีทำคลิป'};
test('deadline uses noon Bangkok, includes exact cutoff and rejects afterward',()=>{assert.equal(DEADLINE,'2026-10-23T05:00:00.000Z');assert.ok(isOpen(Date.parse(DEADLINE)));assert.ok(!isOpen(Date.parse(DEADLINE)+1));});
test('normalizes Thai phone digits and international prefix',()=>{assert.equal(validate({...valid,phone:'๐๘๑ ๒๓๔ ๕๖๗๘'}).phone,'0812345678');assert.equal(validate({...valid,phone:'+66 81 234 5678'}).phone,'0812345678');});
test('all six categories accepted; out of range, blank fields and control chars rejected',()=>{for(let category=1;category<=6;category++)assert.equal(validate({...valid,category}).category,category);for(const changes of [{category:7},{generation:5},{reason:' '},{fullName:'a\u0000b'},{phone:'1234'},{requestId:'x'}])assert.throws(()=>validate({...valid,...changes}));});
test('request identity is tied to every response value',()=>{const a=validate(valid);assert.equal(payloadHash(a),payloadHash(validate({...valid})));assert.notEqual(payloadHash(a),payloadHash(validate({...valid,reason:'เปลี่ยนคำตอบ'})));});
test('CSV neutralizes formula and quote injection',()=>{assert.equal(csvCell('=1+1'),'"\'=1+1"');assert.equal(csvCell('  @SUM(A1)'),'"\'  @SUM(A1)"');assert.equal(csvCell('say "hello"'),'"say ""hello"""');});
test('missing, forged and malformed admin cookies denied',()=>{for(const cookie of ['', 'businessboy_student_story_admin=bad','businessboy_student_story_admin=%ZZ'])assert.equal(authenticated({headers:{cookie}}),false);});
function request(method,query,body,headers={}){return new Promise(async resolve=>{const res={headers:{},setHeader(k,v){this.headers[k]=v;},end(value){resolve({status:this.statusCode,headers:this.headers,data:JSON.parse(value)});}};await handler({method,query,body,headers:{host:'localhost:4391',...headers}},res);});}
test('anonymous users cannot list or export any submissions',async()=>{for(const action of ['list','export'])assert.equal((await request('GET',{action})).status,401);});
test('public config does not include learner data and cross-origin writes rejected',async()=>{const config=await request('GET',{action:'config'});assert.equal(config.status,200);assert.deepEqual(Object.keys(config.data).sort(),['assignment','deadline','open','serverTime']);assert.equal((await request('POST',{action:'submit'},valid,{origin:'https://other.example','content-type':'application/json'})).status,403);});
test('invalid JSON, missing fields and wrong HTTP methods fail before database writes',async()=>{const h={origin:'http://localhost:4391','content-type':'application/json'};assert.equal((await request('POST',{action:'submit'},'{',h)).status,400);assert.equal((await request('POST',{action:'submit'},{...valid,reason:''},h)).status,400);assert.equal((await request('GET',{action:'submit'})).status,405);});

test('long Thai answers and names retain every character beyond the previous limits',()=>{const long='อยากเรียนรู้และทดลองทำเพจด้วยตัวเอง '.repeat(1000);const input={...valid,fullName:'ชื่อ'.repeat(100),facebookName:'ชื่อเฟซบุ๊ก'.repeat(100),pageName:'ชื่อเพจ'.repeat(100),reason:long,discovered:long,decision:long};assert.ok(Buffer.byteLength(JSON.stringify(input))>65000);const result=validate(input);for(const key of ['fullName','facebookName','pageName','reason','discovered','decision'])assert.equal(result[key],input[key].trim());});
test('large valid request reaches storage without an application body-size rejection',async()=>{const h={origin:'http://localhost:4391','content-type':'application/json'};const input={...valid,reason:'คำตอบภาษาไทย '.repeat(10000)};const result=await request('POST',{action:'submit'},JSON.stringify(input),h);assert.equal(result.status,503);assert.match(result.data.error,/ระบบยังไม่พร้อม/);});
