const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const {createClock}=require('../homework-assets/countdown');
const deadline='2026-10-23T05:00:00.000Z';
const configAt=remaining=>({deadline,serverTime:new Date(Date.parse(deadline)-remaining).toISOString(),open:remaining>0});
test('server time is independent of a wrong device date; elapsed time catches up after delayed ticks',()=>{let elapsed=100;const clock=createClock(()=>elapsed);assert.equal(clock.read(),null);clock.sync(configAt(2*86400000+3661000));assert.deepEqual(clock.read(),{expired:false,urgent:false,days:2,hours:1,minutes:1,seconds:1});elapsed+=61000;assert.deepEqual(clock.read(),{expired:false,urgent:false,days:2,hours:1,minutes:0,seconds:0});});
test('24-hour warning, last partial second, exact deadline and negative values',()=>{let elapsed=0;const clock=createClock(()=>elapsed);clock.sync(configAt(86400000));assert.equal(clock.read().urgent,false);elapsed=1;assert.equal(clock.read().urgent,true);clock.sync(configAt(1001));elapsed+=1000;assert.equal(clock.read().seconds,1);assert.equal(clock.read().expired,false);elapsed+=1;assert.equal(clock.read().expired,true);elapsed+=999999;assert.equal(clock.read().seconds,0);});
test('fresh server sync corrects elapsed time and explicit closed state overrides future deadline',()=>{let elapsed=0;const clock=createClock(()=>elapsed);clock.sync(configAt(100000));elapsed=1000;clock.sync({...configAt(90000),open:false});assert.equal(clock.read().expired,true);assert.throws(()=>clock.sync({deadline:'bad',serverTime:'bad',open:true}));assert.equal(clock.read().expired,true);});
function harness(initialConfig){
 const elements=new Map(),intervals=new Map(),events=new Map();let elapsed=0,config=initialConfig;
 const element=key=>{if(!elements.has(key))elements.set(key,{textContent:'',hidden:key==='#closed',disabled:false,value:'คำตอบของผู้เรียนยังอยู่',classList:{toggle(){}},addEventListener(){}});return elements.get(key);};
 const context={HomeworkCountdown:{createClock},performance:{now:()=>elapsed},crypto:{randomUUID:()=> 'qa-uuid'},AbortController,document:{hidden:false,querySelector:element,addEventListener:(type,fn)=>events.set(type,fn)},window:{addEventListener:(type,fn)=>events.set(type,fn)},setInterval:(fn,ms)=>intervals.set(ms,fn),setTimeout:()=>1,clearTimeout(){},fetch:async()=>{if(config===null)throw Error('offline');return {ok:true,json:async()=>config};}};
 vm.runInNewContext(fs.readFileSync(require.resolve('../homework-assets/homework.js'),'utf8'),context);
 return {element,intervals,events,setElapsed:v=>elapsed=v,setConfig:v=>config=v,flush:()=>new Promise(resolve=>setImmediate(resolve))};
}
test('page counts down, warns, disables submission at cutoff and retains written answers',async()=>{const h=harness(configAt(2000));await h.flush();assert.equal(h.element('#countdown-seconds').textContent,'02');assert.match(h.element('#countdown-status').textContent,/วันสุดท้าย/);h.setElapsed(1000);h.intervals.get(1000)();assert.equal(h.element('#countdown-seconds').textContent,'01');h.setElapsed(2000);h.intervals.get(1000)();assert.equal(h.element('#submit-button').disabled,true);assert.equal(h.element('#closed').hidden,false);assert.equal(h.element('#homework-form').hidden,false);assert.equal(h.element('#reason').value,'คำตอบของผู้เรียนยังอยู่');assert.equal(h.element('#countdown-seconds').textContent,'00');});
test('initial network failure never invents a countdown; reconnect recovers',async()=>{const h=harness(null);await h.flush();assert.match(h.element('#countdown-status').textContent,/ยังตรวจสอบเวลาไม่ได้/);h.setConfig(configAt(2*86400000));await h.events.get('online')();assert.equal(h.element('#countdown-days').textContent,'02');});
test('expiry after a completed submission does not replace the successful receipt with a closed notice',async()=>{const h=harness(configAt(1000));await h.flush();h.element('#homework-form').hidden=true;h.setElapsed(2000);h.intervals.get(1000)();assert.equal(h.element('#closed').hidden,true);});
