const test=require('node:test'),assert=require('node:assert/strict');
const handler=require('../api/homework-ep2');const {validate,reviewInput,isOpen,DEADLINE,csvCell}=handler._test;const {normalizePageUrl}=require('../homework-assets/page-url');
const valid={requestId:'cd0c936b-78da-4bde-bf55-d9aaea82556a',fullName:'ผู้เรียนทดสอบ',phone:'0812345678',facebookName:'Test Student',generation:4,pageName:'ชื่อเพจทดสอบ',pageUrl:'facebook.com/testpage'};
test('page registration accepts no videos and cannot set its own review status',()=>{const v=validate({...valid,clipCount:0,review_status:'complete'});assert.equal(v.pageUrl,'https://facebook.com/testpage');assert.equal(v.clipCount,undefined);assert.equal(v.review_status,undefined);assert.equal(validate(valid).pageName,valid.pageName);});
test('accept common page URLs, normalize scheme and remove tracking',()=>{for(const url of ['facebook.com/testpage','https://m.facebook.com/profile.php?id=123456','https://www.facebook.com/pages/Test/123','https://www.facebook.com/share/ABC/','https://fb.me/Test'])assert.ok(normalizePageUrl(url).startsWith('https://'));assert.equal(normalizePageUrl('http://www.facebook.com/Test?mibextid=123#x'),'https://www.facebook.com/Test');});
test('reject video/post/group URLs, malicious protocols and deceptive hosts',()=>{for(const url of ['https://facebook.com/reel/123','https://facebook.com/Test/videos/123','https://facebook.com/Test/posts/123','https://facebook.com/share/v/123','https://facebook.com/groups/123','https://facebook.com/watch?v=123','https://facebook.com/','https://facebook.com/profile.php','https://facebook.com.evil.test/Page','https://facebook.com@evil.test/Page','javascript:alert(1)','https://facebook.com/l.php?u=https://evil.test','https://facebook.com/%72eel/123','https://user:pass@facebook.com/Page','https://facebook.com/Page other'])assert.throws(()=>normalizePageUrl(url),url);});
test('long Thai names are preserved and wrong required fields rejected',()=>{const long='ชื่อภาษาไทย '.repeat(1000);for(const field of ['fullName','facebookName','pageName'])assert.equal(validate({...valid,[field]:long})[field],long.trim());for(const change of [{phone:'123'},{generation:0},{pageName:''},{pageUrl:'https://example.org'},{requestId:'x'}])assert.throws(()=>validate({...valid,...change}));});
test('review allows zero clips but complete requires 30 or more, with a version',()=>{const base={id:valid.requestId,version:0,status:'progress',clipCount:0,note:''};assert.equal(reviewInput(base).count,0);assert.equal(reviewInput({...base,clipCount:null}).count,null);assert.equal(reviewInput({...base,status:'complete',clipCount:30}).status,'complete');for(const change of [{status:'complete'},{status:'complete',clipCount:null},{clipCount:-1},{clipCount:1.5},{version:-1},{status:'unknown'}])assert.throws(()=>reviewInput({...base,...change}));});
function request(method,query,body,headers={}){return new Promise(async resolve=>{const res={headers:{},setHeader(k,v){this.headers[k]=v;},end(value){resolve({status:this.statusCode,headers:this.headers,data:JSON.parse(value)});}};await handler({method,query,body,headers:{host:'localhost:4391',...headers}},res);});}
test('private review/list/export require authentication and CSRF is blocked',async()=>{for(const action of ['list','export'])assert.equal((await request('GET',{action})).status,401);const h={origin:'http://localhost:4391','content-type':'application/json'};for(const action of ['review','archive-test'])assert.equal((await request('POST',{action},{},h)).status,401);assert.equal((await request('POST',{action:'submit'},valid,{...h,origin:'https://evil.test'})).status,403);assert.equal((await request('POST',{action:'submit'},{...valid,pageUrl:'https://facebook.com/reel/123'},h)).data.field,'pageUrl');});
test('public config is EP2 with Bangkok noon deadline and no personal data',async()=>{const result=await request('GET',{action:'config'});assert.equal(result.data.assignment,'gen4-ep2');assert.deepEqual(Object.keys(result.data).sort(),['assignment','deadline','open','serverTime']);assert.equal(DEADLINE,'2026-10-23T05:00:00.000Z');assert.equal(isOpen(Date.parse(DEADLINE)+1),false);assert.equal(csvCell('=1+1'),'"\'=1+1"');});
