'use strict';
const {test,after}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {PGlite}=require('@electric-sql/pglite');
const pg=new PGlite();
const modulePath=require.resolve('@neondatabase/serverless');
function tag(strings,...values){const sql=strings.reduce((a,b,i)=>a+(i?'$'+i:'')+b,'');return {sql,values,then(resolve,reject){return pg.query(sql,values).then(x=>x.rows).then(resolve,reject);}};}
tag.transaction=queries=>pg.transaction(async tx=>{const results=[];for(const q of queries)results.push((await tx.query(q.sql,q.values)).rows);return results;});
require.cache[modulePath]={id:modulePath,filename:modulePath,loaded:true,exports:{neon:()=>tag}};
process.env.STUDENT_STORY_DATABASE_URL='postgresql://offline-test';process.env.STUDENT_STORY_SECRET='offline-test-secret-only';
const handler=require('../api/kvid-assistant'),D=require('../api/_kvid-policy.js'),adminConfig=require('../api/_student-story-admin-config');
const exp=Date.now()+600000;const sig=crypto.createHmac('sha256',process.env.STUDENT_STORY_SECRET).update('admin:'+exp+':'+adminConfig.digest).digest('base64url');
const admin={cookie:`businessboy_student_story_admin=${exp}.${sig}`,origin:'http://localhost:4392','content-type':'application/json'};
const accounts=[];
async function req(action,body,headers={},query={}){return new Promise(resolve=>{const res={headers:{},setHeader(k,v){this.headers[k]=v;},end(data){let parsed;try{parsed=JSON.parse(data);}catch{parsed=data;}resolve({status:this.statusCode,data:parsed,headers:this.headers});}};handler({method:body===undefined?'GET':'POST',query:{action,...query},body,headers:{host:'localhost:4392','content-type':'application/json',...headers}},res);});}
async function register(first='สมชาย',last='ทดสอบ'){const a={id:crypto.randomUUID(),token:crypto.randomBytes(32).toString('base64url'),firstName:first,lastName:last};accounts.push(a);return {a,r:await req('register',a,{authorization:'Bearer '+a.token})};}
const check=a=>req('check',undefined,{authorization:'Bearer '+a.token},{id:a.id});
async function apply(policy){const p=await req('preview',{policy},admin);assert.equal(p.status,200);const r=await req('apply',{policy:p.data.policy,revision:p.data.revision,proof:p.data.proof},admin);assert.equal(r.status,200);return p.data;}

test('normalization is exact; prefixes/space handled without fuzzy matching',()=>{assert.equal(D.key(' นาย สมชาย ','ใจดี'),D.key('สมชาย','ใจดี'));assert.notEqual(D.key('สมชาย','ใจดี'),D.key('สมชาญ','ใจดี'));assert.throws(()=>D.policy({mode:'allowlist',registrationOpen:true,names:[]}));assert.throws(()=>D.policy({mode:'allowlist',registrationOpen:true,names:[{firstName:'นาย สมชาย',lastName:'ใจดี'},{firstName:'สมชาย',lastName:'ใจดี'}]}));});
test('private data/mutations require admin; browser cross-origin change is blocked',async()=>{for(const a of ['list','export','audit'])assert.equal((await req(a)).status,401);for(const a of ['preview','apply','member','qa-cleanup'])assert.equal((await req(a,{})).status,401);assert.equal((await req('preview',{}, {...admin,origin:'https://evil.test'})).status,403);});
test('open registration immediately works, is idempotent, cannot rename/reactivate or impersonate',async()=>{const {a,r}=await register();assert.equal(r.status,201);assert.equal(r.data.allowed,true);assert.equal(r.data.reason,'unverified');assert.equal((await check(a)).data.allowed,true);assert.equal((await req('register',a,{authorization:'Bearer '+a.token})).status,200);assert.equal((await req('register',{...a,firstName:'เปลี่ยนชื่อ'},{authorization:'Bearer '+a.token})).status,409);assert.equal((await check({...a,token:'x'.repeat(43)})).status,401);assert.equal(r.data.token,undefined);});
test('manual suspension blocks checks and repeat registration; re-enable changes version',async()=>{const a=accounts[0],list=await req('list',undefined,admin),m=list.data.items.find(x=>x.id===a.id);assert.equal((await req('member',{id:a.id,version:m.version,suspended:true},admin)).status,200);assert.equal((await check(a)).data.allowed,false);assert.equal((await req('register',a,{authorization:'Bearer '+a.token})).data.allowed,false);assert.equal((await req('member',{id:a.id,version:m.version,suspended:false},admin)).status,409);assert.equal((await req('member',{id:a.id,version:m.version+1,suspended:false},admin)).status,200);});
test('allowlist applies only with valid preview; unmatched new and old users denied; manual deny survives import',async()=>{const a=accounts[0],{a:b}=await register('สมหญิง','ทดสอบ');const p={mode:'allowlist',registrationOpen:true,names:[{firstName:a.firstName,lastName:a.lastName}]};assert.equal((await req('apply',{policy:p,revision:0,proof:'fake'},admin)).status,409);const preview=await req('preview',{policy:p},admin);assert.equal(preview.data.allowed,1);assert.equal(preview.data.blocked,1);await register('บัญชีใหม่','ทดสอบ');assert.equal((await req('apply',{policy:preview.data.policy,revision:preview.data.revision,proof:preview.data.proof},admin)).status,409);await apply(p);assert.equal((await check(a)).data.allowed,true);assert.equal((await check(b)).data.reason,'not_on_list');assert.equal((await register('นอกไฟล์','ทดสอบ')).r.status,403);const m=(await req('list',undefined,admin)).data.items.find(x=>x.id===a.id);await req('member',{id:a.id,version:m.version,suspended:true},admin);await apply(p);assert.equal((await check(a)).data.reason,'suspended');});
test('pause/close registration, audit and policy rollback are effective',async()=>{await apply({mode:'paused',registrationOpen:false,names:[]});assert.equal((await register()).r.status,403);assert.equal((await check(accounts[1])).data.reason,'paused');await apply({mode:'open',registrationOpen:false,names:[]});assert.equal((await check(accounts[1])).data.allowed,true);assert.equal((await register()).r.status,403);const audits=(await req('audit',undefined,admin)).data.items;assert.ok(audits.some(x=>x.action==='member'));assert.ok(audits.some(x=>x.action==='policy'));const old=audits.find(x=>x.action==='policy').before_data;await apply(old);assert.equal((await check(accounts[1])).data.reason,'paused');});
test('public config contains no names or token; CSV output does not expose credential hashes',async()=>{const config=(await req('config')).data;assert.equal(config.names,undefined);const list=(await req('list',undefined,admin)).data;assert.ok(list.items.every(x=>!x.token_hash));const csv=await req('export',undefined,admin);assert.equal(csv.status,200);assert.ok(csv.headers['Content-Type'].includes('csv'));assert.ok(!csv.data.includes(accounts[0].token));assert.equal(D.csvCell('=1+1'),'"\'=1+1"');});
test('synthetic QA cleanup requires its own bearer and cannot delete real student accounts',async()=>{await apply({mode:'open',registrationOpen:true,names:[]});const {a}=await register('ทดสอบระบบ-KVID-QA','ไม่ใช่นักเรียน');assert.equal((await req('qa-self-cleanup',{id:a.id})).status,401);assert.equal((await req('qa-self-cleanup',{id:a.id},{authorization:'Bearer '+accounts[0].token})).data.removed,0);assert.equal((await req('qa-self-cleanup',{id:accounts[0].id},{authorization:'Bearer '+accounts[0].token})).data.removed,0);const before=(await req('list',undefined,admin)).data.policy.revision;assert.equal((await req('qa-self-cleanup',{id:a.id},{authorization:'Bearer '+a.token})).data.removed,1);assert.ok((await req('list',undefined,admin)).data.policy.revision>before);assert.equal((await check(a)).status,401);});
after(async()=>{await pg.close();});
